In this notebook we use the bounding boxes given with the [Imagenet data set](https://www.kaggle.com/c/imagenet-object-localization-challenge) to generate a new sub-set. From the original data set `Imagenet_full` by only keeping the smallest square comprising the bounding boxe we generate `Imagenet_bbox` sub-set

In [1]:
from retinotopy import *
welcome()

Running on GPU :  Tesla V100-SXM2-32GB #GPU= 1
Running on Jean Zay with Tesla V100-SXM2-32GB with DATAROOT='/lustre/fsn1/projects/rech/fsx/uvb28bo/data' and USER='uvb28bo'

------------------------------------------------------------------------------------------
On date 2025-06-20, Running learning on host r6i6n1 with device cuda, pytorch==2.7.0+cu126
------------------------------------------------------------------------------------------
Welcome on Linux-5.14.0-427.76.1.el9_4.x86_64-x86_64-with-glibc2.34

In [2]:
args = Params()
source_data_set_type = 'full'
args.root  = f'{DATAROOT}/Imagenet_{source_data_set_type}' # Directory containing original images
target_data_set_type = 'bbox'
args.target_root = f'{DATAROOT}/Imagenet_{target_data_set_type}' # Directory containing cropped images
os.makedirs(args.target_root, exist_ok=True)
args.folders, args.root, args.target_root#, revlabels_dico

(['val', 'train'],
 '/lustre/fsn1/projects/rech/fsx/uvb28bo/data/Imagenet_full',
 '/lustre/fsn1/projects/rech/fsx/uvb28bo/data/Imagenet_bbox')

## reading localisation metadata

First for the 'train' dataset:

In [3]:
def get_boxes(df, value):
    idx = list(df['ImageId'][df['ImageId'] == value].index)
    bboxes = []
    if idx:
        for i in range(len(df["PredictionString"][idx[0]].split(' '))//5):
            pos =(5*i)
            bboxes.append({'xmin' : int(df["PredictionString"][idx[0]].split(' ')[1 + pos]),
                           'ymin' : int(df["PredictionString"][idx[0]].split(' ')[2 + pos]),
                           'xmax' : int(df["PredictionString"][idx[0]].split(' ')[3 + (5 *i)]),
                           'ymax' : int(df["PredictionString"][idx[0]].split(' ')[4 + (5 *i)])
                                        })
    return bboxes

In [4]:
with open(args.annotations_train, 'r') as csv_file:
    df_data = pd.read_csv(csv_file)
df_data.head()

          ImageId            PredictionString
0  n02017213_7894   n02017213 115 49 448 294
1  n02017213_7261    n02017213 91 42 330 432
2  n02017213_5636  n02017213 230 104 414 224
3  n02017213_6132    n02017213 46 82 464 387
4  n02017213_7659   n02017213 103 66 331 335

In [5]:
get_boxes(df_data, 'n02099849_2300')

[{'xmin': 151, 'ymin': 146, 'xmax': 332, 'ymax': 333},
 {'xmin': 7, 'ymin': 232, 'xmax': 331, 'ymax': 467}]

In [6]:
get_boxes(df_data, 'n01440764_32420')

[]

Now for the 'val' dataset:

In [7]:
with open(args.annotations_val, 'r') as csv_file:
    df_data = pd.read_csv(csv_file)
df_data.head()

,ImageId,PredictionString,origin_size
0,ILSVRC2012_val_00048981,n03995372 85 1 499 272,"(500, 360)"
1,ILSVRC2012_val_00037956,n03481172 131 0 499 254,"(500, 333)"
2,ILSVRC2012_val_00026161,n02108000 38 0 464 280,"(500, 334)"
3,ILSVRC2012_val_00026171,n03109150 0 14 216 299,"(225, 300)"
4,ILSVRC2012_val_00008726,n02119789 255 142 454 329 n02119789 44 21 322 ...,"(500, 357)"

In [8]:
get_boxes(df_data, 'ILSVRC2012_val_00026171')

[{'xmin': 0, 'ymin': 14, 'xmax': 216, 'ymax': 299}]

In [9]:
def clean_list(list_dir, patterns=['.DS_Store', '.ipynb_checkpoints']):
    for pattern in patterns:
        if pattern in list_dir: list_dir.remove(pattern)
    return list_dir

## cropping images

In [10]:
from PIL import Image 

def square_box(xmin, ymin, xmax, ymax):
    temp = ((xmax-xmin)-(ymax-ymin))//2 # signed radius
    if temp > 0 :
        ymin -= temp
        ymax += temp
    else:
        xmin += temp
        xmax -= temp
    return xmin, ymin, xmax, ymax


for folder in args.folders :
    # first level
    print(f'\nFolder \"{folder}\"')
    source_folder = os.path.join(args.root, folder)
    boxes_folder = os.path.join(args.target_root, folder)
    os.makedirs(boxes_folder, exist_ok=True)

    # second level
    with open(f'data/LOC_{folder}_solution.csv', 'r') as csv_file:
        df_data = pd.read_csv(csv_file)
    for i_label, label_id in enumerate(revlabels_dico.keys()):
        print(f'Scraping images for id \"{label_id}\" : {labels[i_label]} ', end='')
        img_source_folder = os.path.join(source_folder, label_id)
        target_folder = os.path.join(boxes_folder, label_id)
        if True: #not os.path.isdir(target_folder):
            os.makedirs(target_folder, exist_ok=True)
            print(os.listdir(img_source_folder))
            for imgs in  clean_list(os.listdir(img_source_folder)):
                data_local = os.path.join(img_source_folder, imgs)
                objects = get_boxes(df_data, imgs.split('.')[0])

                original_image = Image.open(data_local, mode='r').convert('RGB')
                for i_obj, object in enumerate(objects): #if len(obj)  > 0 :
                    xmin = object['xmin']
                    ymin = object['ymin']
                    xmax = object['xmax']
                    ymax = object['ymax']

                    crop_image = original_image.crop(square_box(xmin, ymin, xmax, ymax))
                    no = '' if i_obj==0 else f'_{i_obj}'
                    img_name = imgs.split('.')[0] + no + '.jpg'
                    crop_image.save(os.path.join(target_folder, img_name))

        print(f' - in:  {len(clean_list(os.listdir(img_source_folder)))} / out:  {len(clean_list(os.listdir(target_folder)))}')

Folder "val"
Scraping images for id "n01440764" : tench []
 - in:  0 / out:  0
Scraping images for id "n01443537" : goldfish []
 - in:  0 / out:  0
Scraping images for id "n01484850" : great_white_shark []
 - in:  0 / out:  0
Scraping images for id "n01491361" : tiger_shark []
 - in:  0 / out:  0
Scraping images for id "n01494475" : hammerhead []
 - in:  0 / out:  0
Scraping images for id "n01496331" : electric_ray []
 - in:  0 / out:  0
Scraping images for id "n01498041" : stingray []
 - in:  0 / out:  0
Scraping images for id "n01514668" : cock []
 - in:  0 / out:  0
Scraping images for id "n01514859" : hen []
 - in:  0 / out:  0
Scraping images for id "n01518878" : ostrich []
 - in:  0 / out:  0
Scraping images for id "n01530575" : brambling []
 - in:  0 / out:  0
Scraping images for id "n01531178" : goldfinch []
 - in:  0 / out:  0
Scraping images for id "n01532829" : house_finch []
 - in:  0 / out:  0
Scraping images for id "n01534433" : junco []
 - in:  0 / out:  0
Scraping images for id "n01537544" : indigo_bunting []
 - in:  0 / out:  0
Scraping images for id "n01558993" : robin []
 - in:  0 / out:  0
Scraping images for id "n01560419" : bulbul []
 - in:  0 / out:  0
Scraping images for id "n01580077" : jay []
 - in:  0 / out:  0
Scraping images for id "n01582220" : magpie []
 - in:  0 / out:  0
Scraping images for id "n01592084" : chickadee []
 - in:  0 / out:  0
Scraping images for id "n01601694" : water_ouzel []
 - in:  0 / out:  0
Scraping images for id "n01608432" : kite []
 - in:  0 / out:  0
Scraping images for id "n01614925" : bald_eagle []
 - in:  0 / out:  0
Scraping images for id "n01616318" : vulture []
 - in:  0 / out:  0
Scraping images for id "n01622779" : great_grey_owl []
 - in:  0 / out:  0
Scraping images for id "n01629819" : european_fire_salamander []
 - in:  0 / out:  0
Scraping images for id "n01630670" : common_newt []
 - in:  0 / out:  0
Scraping images for id "n01631663" : eft []
 - in:  0 / out:  0
Scraping images for id "n01632458" : spotted_salamander []
 - in:  0 / out:  0
Scraping images for id "n01632777" : axolotl []
 - in:  0 / out:  0
Scraping images for id "n01641577" : bullfrog []
 - in:  0 / out:  0
Scraping images for id "n01644373" : tree_frog []
 - in:  0 / out:  0
Scraping images for id "n01644900" : tailed_frog []
 - in:  0 / out:  0
Scraping images for id "n01664065" : loggerhead []
 - in:  0 / out:  0
Scraping images for id "n01665541" : leatherback_turtle []
 - in:  0 / out:  0
Scraping images for id "n01667114" : mud_turtle []
 - in:  0 / out:  0
Scraping images for id "n01667778" : terrapin []
 - in:  0 / out:  0
Scraping images for id "n01669191" : box_turtle []
 - in:  0 / out:  0
Scraping images for id "n01675722" : banded_gecko []
 - in:  0 / out:  0
Scraping images for id "n01677366" : common_iguana []
 - in:  0 / out:  0
Scraping images for id "n01682714" : american_chameleon []
 - in:  0 / out:  0
Scraping images for id "n01685808" : whiptail []
 - in:  0 / out:  0
Scraping images for id "n01687978" : agama []
 - in:  0 / out:  0
Scraping images for id "n01688243" : frilled_lizard []
 - in:  0 / out:  0
Scraping images for id "n01689811" : alligator_lizard []
 - in:  0 / out:  0
Scraping images for id "n01692333" : gila_monster []
 - in:  0 / out:  0
Scraping images for id "n01693334" : green_lizard []
 - in:  0 / out:  0
Scraping images for id "n01694178" : african_chameleon []

 - in:  0 / out:  0
Scraping images for id "n01695060" : komodo_dragon []
 - in:  0 / out:  0
Scraping images for id "n01697457" : african_crocodile []
 - in:  0 / out:  0
Scraping images for id "n01698640" : american_alligator []
 - in:  0 / out:  0
Scraping images for id "n01704323" : triceratops []
 - in:  0 / out:  0
Scraping images for id "n01728572" : thunder_snake []
 - in:  0 / out:  0
Scraping images for id "n01728920" : ringneck_snake []
 - in:  0 / out:  0
Scraping images for id "n01729322" : hognose_snake []
 - in:  0 / out:  0
Scraping images for id "n01729977" : green_snake []
 - in:  0 / out:  0
Scraping images for id "n01734418" : king_snake []
 - in:  0 / out:  0
Scraping images for id "n01735189" : garter_snake []
 - in:  0 / out:  0
Scraping images for id "n01737021" : water_snake []
 - in:  0 / out:  0
Scraping images for id "n01739381" : vine_snake []
 - in:  0 / out:  0
Scraping images for id "n01740131" : night_snake []
 - in:  0 / out:  0
Scraping images for id "n01742172" : boa_constrictor []
 - in:  0 / out:  0
Scraping images for id "n01744401" : rock_python []
 - in:  0 / out:  0
Scraping images for id "n01748264" : indian_cobra []
 - in:  0 / out:  0
Scraping images for id "n01749939" : green_mamba []
 - in:  0 / out:  0
Scraping images for id "n01751748" : sea_snake []
 - in:  0 / out:  0
Scraping images for id "n01753488" : horned_viper []
 - in:  0 / out:  0
Scraping images for id "n01755581" : diamondback []
 - in:  0 / out:  0
Scraping images for id "n01756291" : sidewinder []
 - in:  0 / out:  0
Scraping images for id "n01768244" : trilobite []
 - in:  0 / out:  0
Scraping images for id "n01770081" : harvestman []
 - in:  0 / out:  0
Scraping images for id "n01770393" : scorpion []
 - in:  0 / out:  0
Scraping images for id "n01773157" : black_and_gold_garden_spider []
 - in:  0 / out:  0
Scraping images for id "n01773549" : barn_spider []
 - in:  0 / out:  0
Scraping images for id "n01773797" : garden_spider []
 - in:  0 / out:  0
Scraping images for id "n01774384" : black_widow []
 - in:  0 / out:  0
Scraping images for id "n01774750" : tarantula []
 - in:  0 / out:  0
Scraping images for id "n01775062" : wolf_spider []
 - in:  0 / out:  0
Scraping images for id "n01776313" : tick []
 - in:  0 / out:  0
Scraping images for id "n01784675" : centipede []
 - in:  0 / out:  0
Scraping images for id "n01795545" : black_grouse []
 - in:  0 / out:  0
Scraping images for id "n01796340" : ptarmigan []
 - in:  0 / out:  0
Scraping images for id "n01797886" : ruffed_grouse []
 - in:  0 / out:  0
Scraping images for id "n01798484" : prairie_chicken []
 - in:  0 / out:  0
Scraping images for id "n01806143" : peacock []
 - in:  0 / out:  0
Scraping images for id "n01806567" : quail []
 - in:  0 / out:  0
Scraping images for id "n01807496" : partridge []
 - in:  0 / out:  0
Scraping images for id "n01817953" : african_grey []
 - in:  0 / out:  0
Scraping images for id "n01818515" : macaw []
 - in:  0 / out:  0
Scraping images for id "n01819313" : sulphur-crested_cockatoo []
 - in:  0 / out:  0
Scraping images for id "n01820546" : lorikeet []
 - in:  0 / out:  0
Scraping images for id "n01824575" : coucal []
 - in:  0 / out:  0
Scraping images for id "n01828970" : bee_eater []
 - in:  0 / out:  0
Scraping images for id "n01829413" : hornbill []
 - in:  0 / out:  0
Scraping images for id "n01833805" : hummingbird []
 - in:  0 / out:  0
Scraping images for id "n01843065" : jacamar []
 - in:  0 / out:  0
Scraping images for id "n01843383" : toucan []
 - in:  0 / out:  0
Scraping images for id "n01847000" : drake []
 - in:  0 / out:  0
Scraping images for id "n01855032" : red-breasted_merganser []
 - in:  0 / out:  0
Scraping images for id "n01855672" : goose []
 - in:  0 / out:  0
Scraping images for id "n01860187" : black_swan []
 - in:  0 / out:  0
Scraping images for id "n01871265" : tusker []
 - in:  0 / out:  0
Scraping images for id "n01872401" : echidna []
 - in:  0 / out:  0
Scraping images for id "n01873310" : platypus []
 - in:  0 / out:  0
Scraping images for id "n01877812" : wallaby []
 - in:  0 / out:  0
Scraping images for id "n01882714" : koala []
 - in:  0 / out:  0
Scraping images for id "n01883070" : wombat []
 - in:  0 / out:  0
Scraping images for id "n01910747" : jellyfish []
 - in:  0 / out:  0
Scraping images for id "n01914609" : sea_anemone []
 - in:  0 / out:  0
Scraping images for id "n01917289" : brain_coral []
 - in:  0 / out:  0
Scraping images for id "n01924916" : flatworm []
 - in:  0 / out:  0
Scraping images for id "n01930112" : nematode []
 - in:  0 / out:  0
Scraping images for id "n01943899" : conch []
 - in:  0 / out:  0
Scraping images for id "n01944390" : snail []
 - in:  0 / out:  0
Scraping images for id "n01945685" : slug []
 - in:  0 / out:  0
Scraping images for id "n01950731" : sea_slug []
 - in:  0 / out:  0
Scraping images for id "n01955084" : chiton []
 - in:  0 / out:  0
Scraping images for id "n01968897" : chambered_nautilus []
 - in:  0 / out:  0
Scraping images for id "n01978287" : dungeness_crab []
 - in:  0 / out:  0
Scraping images for id "n01978455" : rock_crab []
 - in:  0 / out:  0
Scraping images for id "n01980166" : fiddler_crab []
 - in:  0 / out:  0
Scraping images for id "n01981276" : king_crab []
 - in:  0 / out:  0
Scraping images for id "n01983481" : american_lobster []
 - in:  0 / out:  0
Scraping images for id "n01984695" : spiny_lobster []
 - in:  0 / out:  0
Scraping images for id "n01985128" : crayfish []
 - in:  0 / out:  0
Scraping images for id "n01986214" : hermit_crab []
 - in:  0 / out:  0
Scraping images for id "n01990800" : isopod []
 - in:  0 / out:  0
Scraping images for id "n02002556" : white_stork

[]
 - in:  0 / out:  0
Scraping images for id "n02002724" : black_stork []
 - in:  0 / out:  0
Scraping images for id "n02006656" : spoonbill []
 - in:  0 / out:  0
Scraping images for id "n02007558" : flamingo []
 - in:  0 / out:  0
Scraping images for id "n02009229" : little_blue_heron []
 - in:  0 / out:  0
Scraping images for id "n02009912" : american_egret []
 - in:  0 / out:  0
Scraping images for id "n02011460" : bittern []
 - in:  0 / out:  0
Scraping images for id "n02012849" : crane []
 - in:  0 / out:  0
Scraping images for id "n02013706" : limpkin []
 - in:  0 / out:  0
Scraping images for id "n02017213" : european_gallinule []
 - in:  0 / out:  0
Scraping images for id "n02018207" : american_coot []
 - in:  0 / out:  0
Scraping images for id "n02018795" : bustard []
 - in:  0 / out:  0
Scraping images for id "n02025239" : ruddy_turnstone []
 - in:  0 / out:  0
Scraping images for id "n02027492" : red-backed_sandpiper []
 - in:  0 / out:  0
Scraping images for id "n02028035" : redshank []
 - in:  0 / out:  0
Scraping images for id "n02033041" : dowitcher []
 - in:  0 / out:  0
Scraping images for id "n02037110" : oystercatcher []
 - in:  0 / out:  0
Scraping images for id "n02051845" : pelican []
 - in:  0 / out:  0
Scraping images for id "n02056570" : king_penguin []
 - in:  0 / out:  0
Scraping images for id "n02058221" : albatross []
 - in:  0 / out:  0
Scraping images for id "n02066245" : grey_whale []
 - in:  0 / out:  0
Scraping images for id "n02071294" : killer_whale []
 - in:  0 / out:  0
Scraping images for id "n02074367" : dugong []
 - in:  0 / out:  0
Scraping images for id "n02077923" : sea_lion []
 - in:  0 / out:  0
Scraping images for id "n02085620" : chihuahua []
 - in:  0 / out:  0
Scraping images for id "n02085782" : japanese_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02085936" : maltese_dog []
 - in:  0 / out:  0
Scraping images for id "n02086079" : pekinese []
 - in:  0 / out:  0
Scraping images for id "n02086240" : shih-tzu []
 - in:  0 / out:  0
Scraping images for id "n02086646" : blenheim_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02086910" : papillon []
 - in:  0 / out:  0
Scraping images for id "n02087046" : toy_terrier []
 - in:  0 / out:  0
Scraping images for id "n02087394" : rhodesian_ridgeback []
 - in:  0 / out:  0
Scraping images for id "n02088094" : afghan_hound []
 - in:  0 / out:  0
Scraping images for id "n02088238" : basset []
 - in:  0 / out:  0
Scraping images for id "n02088364" : beagle []
 - in:  0 / out:  0
Scraping images for id "n02088466" : bloodhound []
 - in:  0 / out:  0
Scraping images for id "n02088632" : bluetick []
 - in:  0 / out:  0
Scraping images for id "n02089078" : black-and-tan_coonhound []
 - in:  0 / out:  0
Scraping images for id "n02089867" : walker_hound []
 - in:  0 / out:  0
Scraping images for id "n02089973" : english_foxhound []
 - in:  0 / out:  0
Scraping images for id "n02090379" : redbone []
 - in:  0 / out:  0
Scraping images for id "n02090622" : borzoi []
 - in:  0 / out:  0
Scraping images for id "n02090721" : irish_wolfhound []
 - in:  0 / out:  0
Scraping images for id "n02091032" : italian_greyhound []
 - in:  0 / out:  0
Scraping images for id "n02091134" : whippet []
 - in:  0 / out:  0
Scraping images for id "n02091244" : ibizan_hound []
 - in:  0 / out:  0
Scraping images for id "n02091467" : norwegian_elkhound []
 - in:  0 / out:  0
Scraping images for id "n02091635" : otterhound []
 - in:  0 / out:  0
Scraping images for id "n02091831" : saluki []
 - in:  0 / out:  0
Scraping images for id "n02092002" : scottish_deerhound []
 - in:  0 / out:  0
Scraping images for id "n02092339" : weimaraner []
 - in:  0 / out:  0
Scraping images for id "n02093256" : staffordshire_bullterrier []
 - in:  0 / out:  0
Scraping images for id "n02093428" : american_staffordshire_terrier []
 - in:  0 / out:  0
Scraping images for id "n02093647" : bedlington_terrier []
 - in:  0 / out:  0
Scraping images for id "n02093754" : border_terrier []
 - in:  0 / out:  0
Scraping images for id "n02093859" : kerry_blue_terrier []
 - in:  0 / out:  0
Scraping images for id "n02093991" : irish_terrier []
 - in:  0 / out:  0
Scraping images for id "n02094114" : norfolk_terrier []
 - in:  0 / out:  0
Scraping images for id "n02094258" : norwich_terrier []
 - in:  0 / out:  0
Scraping images for id "n02094433" : yorkshire_terrier []
 - in:  0 / out:  0
Scraping images for id "n02095314" : wire-haired_fox_terrier []
 - in:  0 / out:  0
Scraping images for id "n02095570" : lakeland_terrier []
 - in:  0 / out:  0
Scraping images for id "n02095889" : sealyham_terrier []
 - in:  0 / out:  0
Scraping images for id "n02096051" : airedale []
 - in:  0 / out:  0
Scraping images for id "n02096177" : cairn []
 - in:  0 / out:  0
Scraping images for id "n02096294" : australian_terrier []
 - in:  0 / out:  0
Scraping images for id "n02096437" : dandie_dinmont []
 - in:  0 / out:  0
Scraping images for id "n02096585" : boston_bull []
 - in:  0 / out:  0
Scraping images for id "n02097047" : miniature_schnauzer []
 - in:  0 / out:  0
Scraping images for id "n02097130" : giant_schnauzer []
 - in:  0 / out:  0
Scraping images for id "n02097209" : standard_schnauzer []
 - in:  0 / out:  0
Scraping images for id "n02097298" : scotch_terrier []
 - in:  0 / out:  0
Scraping images for id "n02097474" : tibetan_terrier []
 - in:  0 / out:  0
Scraping images for id "n02097658" : silky_terrier []
 - in:  0 / out:  0
Scraping images for id "n02098105" : soft-coated_wheaten_terrier []
 - in:  0 / out:  0
Scraping images for id "n02098286" : west_highland_white_terrier []
 - in:  0 / out:  0
Scraping images for id "n02098413" : lhasa []
 - in:  0 / out:  0
Scraping images for id "n02099267" : flat-coated_retriever []
 - in:  0 / out:  0
Scraping images for id "n02099429" : curly-coated_retriever []
 - in:  0 / out:  0
Scraping images for id "n02099601" : golden_retriever []
 - in:  0 / out:  0
Scraping images for id "n02099712" : labrador_retriever []

 - in:  0 / out:  0
Scraping images for id "n02099849" : chesapeake_bay_retriever []
 - in:  0 / out:  0
Scraping images for id "n02100236" : german_short-haired_pointer []
 - in:  0 / out:  0
Scraping images for id "n02100583" : vizsla []
 - in:  0 / out:  0
Scraping images for id "n02100735" : english_setter []
 - in:  0 / out:  0
Scraping images for id "n02100877" : irish_setter []
 - in:  0 / out:  0
Scraping images for id "n02101006" : gordon_setter []
 - in:  0 / out:  0
Scraping images for id "n02101388" : brittany_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02101556" : clumber []
 - in:  0 / out:  0
Scraping images for id "n02102040" : english_springer []
 - in:  0 / out:  0
Scraping images for id "n02102177" : welsh_springer_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02102318" : cocker_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02102480" : sussex_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02102973" : irish_water_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02104029" : kuvasz []
 - in:  0 / out:  0
Scraping images for id "n02104365" : schipperke []
 - in:  0 / out:  0
Scraping images for id "n02105056" : groenendael []
 - in:  0 / out:  0
Scraping images for id "n02105162" : malinois []
 - in:  0 / out:  0
Scraping images for id "n02105251" : briard []
 - in:  0 / out:  0
Scraping images for id "n02105412" : kelpie []
 - in:  0 / out:  0
Scraping images for id "n02105505" : komondor []
 - in:  0 / out:  0
Scraping images for id "n02105641" : old_english_sheepdog []
 - in:  0 / out:  0
Scraping images for id "n02105855" : shetland_sheepdog []
 - in:  0 / out:  0
Scraping images for id "n02106030" : collie []
 - in:  0 / out:  0
Scraping images for id "n02106166" : border_collie []
 - in:  0 / out:  0
Scraping images for id "n02106382" : bouvier_des_flandres []
 - in:  0 / out:  0
Scraping images for id "n02106550" : rottweiler []
 - in:  0 / out:  0
Scraping images for id "n02106662" : german_shepherd []
 - in:  0 / out:  0
Scraping images for id "n02107142" : doberman []
 - in:  0 / out:  0
Scraping images for id "n02107312" : miniature_pinscher []
 - in:  0 / out:  0
Scraping images for id "n02107574" : greater_swiss_mountain_dog []
 - in:  0 / out:  0
Scraping images for id "n02107683" : bernese_mountain_dog []
 - in:  0 / out:  0
Scraping images for id "n02107908" : appenzeller []
 - in:  0 / out:  0
Scraping images for id "n02108000" : entlebucher []
 - in:  0 / out:  0
Scraping images for id "n02108089" : boxer []
 - in:  0 / out:  0
Scraping images for id "n02108422" : bull_mastiff []
 - in:  0 / out:  0
Scraping images for id "n02108551" : tibetan_mastiff []
 - in:  0 / out:  0
Scraping images for id "n02108915" : french_bulldog []
 - in:  0 / out:  0
Scraping images for id "n02109047" : great_dane []
 - in:  0 / out:  0
Scraping images for id "n02109525" : saint_bernard []
 - in:  0 / out:  0
Scraping images for id "n02109961" : eskimo_dog []
 - in:  0 / out:  0
Scraping images for id "n02110063" : malamute []
 - in:  0 / out:  0
Scraping images for id "n02110185" : siberian_husky []
 - in:  0 / out:  0
Scraping images for id "n02110341" : dalmatian []
 - in:  0 / out:  0
Scraping images for id "n02110627" : affenpinscher []
 - in:  0 / out:  0
Scraping images for id "n02110806" : basenji []
 - in:  0 / out:  0
Scraping images for id "n02110958" : pug []
 - in:  0 / out:  0
Scraping images for id "n02111129" : leonberg []
 - in:  0 / out:  0
Scraping images for id "n02111277" : newfoundland []
 - in:  0 / out:  0
Scraping images for id "n02111500" : great_pyrenees []
 - in:  0 / out:  0
Scraping images for id "n02111889" : samoyed []
 - in:  0 / out:  0
Scraping images for id "n02112018" : pomeranian []
 - in:  0 / out:  0
Scraping images for id "n02112137" : chow []
 - in:  0 / out:  0
Scraping images for id "n02112350" : keeshond []
 - in:  0 / out:  0
Scraping images for id "n02112706" : brabancon_griffon []
 - in:  0 / out:  0
Scraping images for id "n02113023" : pembroke []
 - in:  0 / out:  0
Scraping images for id "n02113186" : cardigan []
 - in:  0 / out:  0
Scraping images for id "n02113624" : toy_poodle []
 - in:  0 / out:  0
Scraping images for id "n02113712" : miniature_poodle []
 - in:  0 / out:  0
Scraping images for id "n02113799" : standard_poodle []
 - in:  0 / out:  0
Scraping images for id "n02113978" : mexican_hairless []
 - in:  0 / out:  0
Scraping images for id "n02114367" : timber_wolf []
 - in:  0 / out:  0
Scraping images for id "n02114548" : white_wolf []
 - in:  0 / out:  0
Scraping images for id "n02114712" : red_wolf []
 - in:  0 / out:  0
Scraping images for id "n02114855" : coyote []
 - in:  0 / out:  0
Scraping images for id "n02115641" : dingo []
 - in:  0 / out:  0
Scraping images for id "n02115913" : dhole []
 - in:  0 / out:  0
Scraping images for id "n02116738" : african_hunting_dog []
 - in:  0 / out:  0
Scraping images for id "n02117135" : hyena []
 - in:  0 / out:  0
Scraping images for id "n02119022" : red_fox []
 - in:  0 / out:  0
Scraping images for id "n02119789" : kit_fox []
 - in:  0 / out:  0
Scraping images for id "n02120079" : arctic_fox []
 - in:  0 / out:  0
Scraping images for id "n02120505" : grey_fox []
 - in:  0 / out:  0
Scraping images for id "n02123045" : tabby []
 - in:  0 / out:  0
Scraping images for id "n02123159" : tiger_cat []
 - in:  0 / out:  0
Scraping images for id "n02123394" : persian_cat []
 - in:  0 / out:  0
Scraping images for id "n02123597" : siamese_cat []
 - in:  0 / out:  0
Scraping images for id "n02124075" : egyptian_cat []
 - in:  0 / out:  0
Scraping images for id "n02125311" : cougar []

 - in:  0 / out:  0
Scraping images for id "n02127052" : lynx []
 - in:  0 / out:  0
Scraping images for id "n02128385" : leopard []
 - in:  0 / out:  0
Scraping images for id "n02128757" : snow_leopard []
 - in:  0 / out:  0
Scraping images for id "n02128925" : jaguar []
 - in:  0 / out:  0
Scraping images for id "n02129165" : lion []
 - in:  0 / out:  0
Scraping images for id "n02129604" : tiger []
 - in:  0 / out:  0
Scraping images for id "n02130308" : cheetah []
 - in:  0 / out:  0
Scraping images for id "n02132136" : brown_bear []
 - in:  0 / out:  0
Scraping images for id "n02133161" : american_black_bear []
 - in:  0 / out:  0
Scraping images for id "n02134084" : ice_bear []
 - in:  0 / out:  0
Scraping images for id "n02134418" : sloth_bear []
 - in:  0 / out:  0
Scraping images for id "n02137549" : mongoose []
 - in:  0 / out:  0
Scraping images for id "n02138441" : meerkat []
 - in:  0 / out:  0
Scraping images for id "n02165105" : tiger_beetle []
 - in:  0 / out:  0
Scraping images for id "n02165456" : ladybug []
 - in:  0 / out:  0
Scraping images for id "n02167151" : ground_beetle []
 - in:  0 / out:  0
Scraping images for id "n02168699" : long-horned_beetle []
 - in:  0 / out:  0
Scraping images for id "n02169497" : leaf_beetle []
 - in:  0 / out:  0
Scraping images for id "n02172182" : dung_beetle []
 - in:  0 / out:  0
Scraping images for id "n02174001" : rhinoceros_beetle []
 - in:  0 / out:  0
Scraping images for id "n02177972" : weevil []
 - in:  0 / out:  0
Scraping images for id "n02190166" : fly []
 - in:  0 / out:  0
Scraping images for id "n02206856" : bee []
 - in:  0 / out:  0
Scraping images for id "n02219486" : ant []
 - in:  0 / out:  0
Scraping images for id "n02226429" : grasshopper []
 - in:  0 / out:  0
Scraping images for id "n02229544" : cricket []
 - in:  0 / out:  0
Scraping images for id "n02231487" : walking_stick []
 - in:  0 / out:  0
Scraping images for id "n02233338" : cockroach []
 - in:  0 / out:  0
Scraping images for id "n02236044" : mantis []
 - in:  0 / out:  0
Scraping images for id "n02256656" : cicada []
 - in:  0 / out:  0
Scraping images for id "n02259212" : leafhopper []
 - in:  0 / out:  0
Scraping images for id "n02264363" : lacewing []
 - in:  0 / out:  0
Scraping images for id "n02268443" : dragonfly []
 - in:  0 / out:  0
Scraping images for id "n02268853" : damselfly []
 - in:  0 / out:  0
Scraping images for id "n02276258" : admiral []
 - in:  0 / out:  0
Scraping images for id "n02277742" : ringlet []
 - in:  0 / out:  0
Scraping images for id "n02279972" : monarch []
 - in:  0 / out:  0
Scraping images for id "n02280649" : cabbage_butterfly []
 - in:  0 / out:  0
Scraping images for id "n02281406" : sulphur_butterfly []
 - in:  0 / out:  0
Scraping images for id "n02281787" : lycaenid []
 - in:  0 / out:  0
Scraping images for id "n02317335" : starfish []
 - in:  0 / out:  0
Scraping images for id "n02319095" : sea_urchin []
 - in:  0 / out:  0
Scraping images for id "n02321529" : sea_cucumber []
 - in:  0 / out:  0
Scraping images for id "n02325366" : wood_rabbit []
 - in:  0 / out:  0
Scraping images for id "n02326432" : hare []
 - in:  0 / out:  0
Scraping images for id "n02328150" : angora []
 - in:  0 / out:  0
Scraping images for id "n02342885" : hamster []
 - in:  0 / out:  0
Scraping images for id "n02346627" : porcupine []
 - in:  0 / out:  0
Scraping images for id "n02356798" : fox_squirrel []
 - in:  0 / out:  0
Scraping images for id "n02361337" : marmot []
 - in:  0 / out:  0
Scraping images for id "n02363005" : beaver []
 - in:  0 / out:  0
Scraping images for id "n02364673" : guinea_pig []
 - in:  0 / out:  0
Scraping images for id "n02389026" : sorrel []
 - in:  0 / out:  0
Scraping images for id "n02391049" : zebra []
 - in:  0 / out:  0
Scraping images for id "n02395406" : hog []
 - in:  0 / out:  0
Scraping images for id "n02396427" : wild_boar []
 - in:  0 / out:  0
Scraping images for id "n02397096" : warthog []
 - in:  0 / out:  0
Scraping images for id "n02398521" : hippopotamus []
 - in:  0 / out:  0
Scraping images for id "n02403003" : ox []
 - in:  0 / out:  0
Scraping images for id "n02408429" : water_buffalo []
 - in:  0 / out:  0
Scraping images for id "n02410509" : bison []
 - in:  0 / out:  0
Scraping images for id "n02412080" : ram []
 - in:  0 / out:  0
Scraping images for id "n02415577" : bighorn []
 - in:  0 / out:  0
Scraping images for id "n02417914" : ibex []
 - in:  0 / out:  0
Scraping images for id "n02422106" : hartebeest []
 - in:  0 / out:  0
Scraping images for id "n02422699" : impala []
 - in:  0 / out:  0
Scraping images for id "n02423022" : gazelle []
 - in:  0 / out:  0
Scraping images for id "n02437312" : arabian_camel []
 - in:  0 / out:  0
Scraping images for id "n02437616" : llama []
 - in:  0 / out:  0
Scraping images for id "n02441942" : weasel []
 - in:  0 / out:  0
Scraping images for id "n02442845" : mink []
 - in:  0 / out:  0
Scraping images for id "n02443114" : polecat []
 - in:  0 / out:  0
Scraping images for id "n02443484" : black-footed_ferret []
 - in:  0 / out:  0
Scraping images for id "n02444819" : otter []
 - in:  0 / out:  0
Scraping images for id "n02445715" : skunk []
 - in:  0 / out:  0
Scraping images for id "n02447366" : badger []
 - in:  0 / out:  0
Scraping images for id "n02454379" : armadillo []
 - in:  0 / out:  0
Scraping images for id "n02457408" : three-toed_sloth []
 - in:  0 / out:  0
Scraping images for id "n02480495" : orangutan []
 - in:  0 / out:  0
Scraping images for id "n02480855" : gorilla []
 - in:  0 / out:  0
Scraping images for id "n02481823" : chimpanzee []

 - in:  0 / out:  0
Scraping images for id "n02483362" : gibbon []
 - in:  0 / out:  0
Scraping images for id "n02483708" : siamang []
 - in:  0 / out:  0
Scraping images for id "n02484975" : guenon []
 - in:  0 / out:  0
Scraping images for id "n02486261" : patas []
 - in:  0 / out:  0
Scraping images for id "n02486410" : baboon []
 - in:  0 / out:  0
Scraping images for id "n02487347" : macaque []
 - in:  0 / out:  0
Scraping images for id "n02488291" : langur []
 - in:  0 / out:  0
Scraping images for id "n02488702" : colobus []
 - in:  0 / out:  0
Scraping images for id "n02489166" : proboscis_monkey []
 - in:  0 / out:  0
Scraping images for id "n02490219" : marmoset []
 - in:  0 / out:  0
Scraping images for id "n02492035" : capuchin []
 - in:  0 / out:  0
Scraping images for id "n02492660" : howler_monkey []
 - in:  0 / out:  0
Scraping images for id "n02493509" : titi []
 - in:  0 / out:  0
Scraping images for id "n02493793" : spider_monkey []
 - in:  0 / out:  0
Scraping images for id "n02494079" : squirrel_monkey []
 - in:  0 / out:  0
Scraping images for id "n02497673" : madagascar_cat []
 - in:  0 / out:  0
Scraping images for id "n02500267" : indri []
 - in:  0 / out:  0
Scraping images for id "n02504013" : indian_elephant []
 - in:  0 / out:  0
Scraping images for id "n02504458" : african_elephant []
 - in:  0 / out:  0
Scraping images for id "n02509815" : lesser_panda []
 - in:  0 / out:  0
Scraping images for id "n02510455" : giant_panda []
 - in:  0 / out:  0
Scraping images for id "n02514041" : barracouta []
 - in:  0 / out:  0
Scraping images for id "n02526121" : eel []
 - in:  0 / out:  0
Scraping images for id "n02536864" : coho []
 - in:  0 / out:  0
Scraping images for id "n02606052" : rock_beauty []
 - in:  0 / out:  0
Scraping images for id "n02607072" : anemone_fish []
 - in:  0 / out:  0
Scraping images for id "n02640242" : sturgeon []
 - in:  0 / out:  0
Scraping images for id "n02641379" : gar []
 - in:  0 / out:  0
Scraping images for id "n02643566" : lionfish []
 - in:  0 / out:  0
Scraping images for id "n02655020" : puffer []
 - in:  0 / out:  0
Scraping images for id "n02666196" : abacus []
 - in:  0 / out:  0
Scraping images for id "n02667093" : abaya []
 - in:  0 / out:  0
Scraping images for id "n02669723" : academic_gown []
 - in:  0 / out:  0
Scraping images for id "n02672831" : accordion []
 - in:  0 / out:  0
Scraping images for id "n02676566" : acoustic_guitar []
 - in:  0 / out:  0
Scraping images for id "n02687172" : aircraft_carrier []
 - in:  0 / out:  0
Scraping images for id "n02690373" : airliner []
 - in:  0 / out:  0
Scraping images for id "n02692877" : airship []
 - in:  0 / out:  0
Scraping images for id "n02699494" : altar []
 - in:  0 / out:  0
Scraping images for id "n02701002" : ambulance []
 - in:  0 / out:  0
Scraping images for id "n02704792" : amphibian []
 - in:  0 / out:  0
Scraping images for id "n02708093" : analog_clock []
 - in:  0 / out:  0
Scraping images for id "n02727426" : apiary []
 - in:  0 / out:  0
Scraping images for id "n02730930" : apron []
 - in:  0 / out:  0
Scraping images for id "n02747177" : ashcan []
 - in:  0 / out:  0
Scraping images for id "n02749479" : assault_rifle []
 - in:  0 / out:  0
Scraping images for id "n02769748" : backpack []
 - in:  0 / out:  0
Scraping images for id "n02776631" : bakery []
 - in:  0 / out:  0
Scraping images for id "n02777292" : balance_beam []
 - in:  0 / out:  0
Scraping images for id "n02782093" : balloon []
 - in:  0 / out:  0
Scraping images for id "n02783161" : ballpoint []
 - in:  0 / out:  0
Scraping images for id "n02786058" : band_aid []
 - in:  0 / out:  0
Scraping images for id "n02787622" : banjo []
 - in:  0 / out:  0
Scraping images for id "n02788148" : bannister []
 - in:  0 / out:  0
Scraping images for id "n02790996" : barbell []
 - in:  0 / out:  0
Scraping images for id "n02791124" : barber_chair []
 - in:  0 / out:  0
Scraping images for id "n02791270" : barbershop []
 - in:  0 / out:  0
Scraping images for id "n02793495" : barn []
 - in:  0 / out:  0
Scraping images for id "n02794156" : barometer []
 - in:  0 / out:  0
Scraping images for id "n02795169" : barrel []
 - in:  0 / out:  0
Scraping images for id "n02797295" : barrow []
 - in:  0 / out:  0
Scraping images for id "n02799071" : baseball []
 - in:  0 / out:  0
Scraping images for id "n02802426" : basketball []
 - in:  0 / out:  0
Scraping images for id "n02804414" : bassinet []
 - in:  0 / out:  0
Scraping images for id "n02804610" : bassoon []
 - in:  0 / out:  0
Scraping images for id "n02807133" : bathing_cap []
 - in:  0 / out:  0
Scraping images for id "n02808304" : bath_towel []
 - in:  0 / out:  0
Scraping images for id "n02808440" : bathtub []
 - in:  0 / out:  0
Scraping images for id "n02814533" : beach_wagon []
 - in:  0 / out:  0
Scraping images for id "n02814860" : beacon []
 - in:  0 / out:  0
Scraping images for id "n02815834" : beaker []
 - in:  0 / out:  0
Scraping images for id "n02817516" : bearskin []
 - in:  0 / out:  0
Scraping images for id "n02823428" : beer_bottle []
 - in:  0 / out:  0
Scraping images for id "n02823750" : beer_glass []
 - in:  0 / out:  0
Scraping images for id "n02825657" : bell_cote []
 - in:  0 / out:  0
Scraping images for id "n02834397" : bib []
 - in:  0 / out:  0
Scraping images for id "n02835271" : bicycle-built-for-two []
 - in:  0 / out:  0
Scraping images for id "n02837789" : bikini []
 - in:  0 / out:  0
Scraping images for id "n02840245" : binder []

 - in:  0 / out:  0
Scraping images for id "n02841315" : binoculars []
 - in:  0 / out:  0
Scraping images for id "n02843684" : birdhouse []
 - in:  0 / out:  0
Scraping images for id "n02859443" : boathouse []
 - in:  0 / out:  0
Scraping images for id "n02860847" : bobsled []
 - in:  0 / out:  0
Scraping images for id "n02865351" : bolo_tie []
 - in:  0 / out:  0
Scraping images for id "n02869837" : bonnet []
 - in:  0 / out:  0
Scraping images for id "n02870880" : bookcase []
 - in:  0 / out:  0
Scraping images for id "n02871525" : bookshop []
 - in:  0 / out:  0
Scraping images for id "n02877765" : bottlecap []
 - in:  0 / out:  0
Scraping images for id "n02879718" : bow []
 - in:  0 / out:  0
Scraping images for id "n02883205" : bow_tie []
 - in:  0 / out:  0
Scraping images for id "n02892201" : brass []
 - in:  0 / out:  0
Scraping images for id "n02892767" : brassiere []
 - in:  0 / out:  0
Scraping images for id "n02894605" : breakwater []
 - in:  0 / out:  0
Scraping images for id "n02895154" : breastplate []
 - in:  0 / out:  0
Scraping images for id "n02906734" : broom []
 - in:  0 / out:  0
Scraping images for id "n02909870" : bucket []
 - in:  0 / out:  0
Scraping images for id "n02910353" : buckle []
 - in:  0 / out:  0
Scraping images for id "n02916936" : bulletproof_vest []
 - in:  0 / out:  0
Scraping images for id "n02917067" : bullet_train []
 - in:  0 / out:  0
Scraping images for id "n02927161" : butcher_shop []
 - in:  0 / out:  0
Scraping images for id "n02930766" : cab []
 - in:  0 / out:  0
Scraping images for id "n02939185" : caldron []
 - in:  0 / out:  0
Scraping images for id "n02948072" : candle []
 - in:  0 / out:  0
Scraping images for id "n02950826" : cannon []
 - in:  0 / out:  0
Scraping images for id "n02951358" : canoe []
 - in:  0 / out:  0
Scraping images for id "n02951585" : can_opener []
 - in:  0 / out:  0
Scraping images for id "n02963159" : cardigan []
 - in:  0 / out:  0
Scraping images for id "n02965783" : car_mirror []
 - in:  0 / out:  0
Scraping images for id "n02966193" : carousel []
 - in:  0 / out:  0
Scraping images for id "n02966687" : carpenter's_kit []
 - in:  0 / out:  0
Scraping images for id "n02971356" : carton []
 - in:  0 / out:  0
Scraping images for id "n02974003" : car_wheel []
 - in:  0 / out:  0
Scraping images for id "n02977058" : cash_machine []
 - in:  0 / out:  0
Scraping images for id "n02978881" : cassette []
 - in:  0 / out:  0
Scraping images for id "n02979186" : cassette_player []
 - in:  0 / out:  0
Scraping images for id "n02980441" : castle []
 - in:  0 / out:  0
Scraping images for id "n02981792" : catamaran []
 - in:  0 / out:  0
Scraping images for id "n02988304" : cd_player []
 - in:  0 / out:  0
Scraping images for id "n02992211" : cello []
 - in:  0 / out:  0
Scraping images for id "n02992529" : cellular_telephone []
 - in:  0 / out:  0
Scraping images for id "n02999410" : chain []
 - in:  0 / out:  0
Scraping images for id "n03000134" : chainlink_fence []
 - in:  0 / out:  0
Scraping images for id "n03000247" : chain_mail []
 - in:  0 / out:  0
Scraping images for id "n03000684" : chain_saw []
 - in:  0 / out:  0
Scraping images for id "n03014705" : chest []
 - in:  0 / out:  0
Scraping images for id "n03016953" : chiffonier []
 - in:  0 / out:  0
Scraping images for id "n03017168" : chime []
 - in:  0 / out:  0
Scraping images for id "n03018349" : china_cabinet []
 - in:  0 / out:  0
Scraping images for id "n03026506" : christmas_stocking []
 - in:  0 / out:  0
Scraping images for id "n03028079" : church []
 - in:  0 / out:  0
Scraping images for id "n03032252" : cinema []
 - in:  0 / out:  0
Scraping images for id "n03041632" : cleaver []
 - in:  0 / out:  0
Scraping images for id "n03042490" : cliff_dwelling []
 - in:  0 / out:  0
Scraping images for id "n03045698" : cloak []
 - in:  0 / out:  0
Scraping images for id "n03047690" : clog []
 - in:  0 / out:  0
Scraping images for id "n03062245" : cocktail_shaker []
 - in:  0 / out:  0
Scraping images for id "n03063599" : coffee_mug []
 - in:  0 / out:  0
Scraping images for id "n03063689" : coffeepot []
 - in:  0 / out:  0
Scraping images for id "n03065424" : coil []
 - in:  0 / out:  0
Scraping images for id "n03075370" : combination_lock []
 - in:  0 / out:  0
Scraping images for id "n03085013" : computer_keyboard []
 - in:  0 / out:  0
Scraping images for id "n03089624" : confectionery []
 - in:  0 / out:  0
Scraping images for id "n03095699" : container_ship []
 - in:  0 / out:  0
Scraping images for id "n03100240" : convertible []
 - in:  0 / out:  0
Scraping images for id "n03109150" : corkscrew []
 - in:  0 / out:  0
Scraping images for id "n03110669" : cornet []
 - in:  0 / out:  0
Scraping images for id "n03124043" : cowboy_boot []
 - in:  0 / out:  0
Scraping images for id "n03124170" : cowboy_hat []
 - in:  0 / out:  0
Scraping images for id "n03125729" : cradle []
 - in:  0 / out:  0
Scraping images for id "n03126707" : crane []
 - in:  0 / out:  0
Scraping images for id "n03127747" : crash_helmet []
 - in:  0 / out:  0
Scraping images for id "n03127925" : crate []
 - in:  0 / out:  0
Scraping images for id "n03131574" : crib []
 - in:  0 / out:  0
Scraping images for id "n03133878" : crock_pot []
 - in:  0 / out:  0
Scraping images for id "n03134739" : croquet_ball []
 - in:  0 / out:  0
Scraping images for id "n03141823" : crutch []
 - in:  0 / out:  0
Scraping images for id "n03146219" : cuirass []

 - in:  0 / out:  0
Scraping images for id "n03160309" : dam []
 - in:  0 / out:  0
Scraping images for id "n03179701" : desk []
 - in:  0 / out:  0
Scraping images for id "n03180011" : desktop_computer []
 - in:  0 / out:  0
Scraping images for id "n03187595" : dial_telephone []
 - in:  0 / out:  0
Scraping images for id "n03188531" : diaper []
 - in:  0 / out:  0
Scraping images for id "n03196217" : digital_clock []
 - in:  0 / out:  0
Scraping images for id "n03197337" : digital_watch []
 - in:  0 / out:  0
Scraping images for id "n03201208" : dining_table []
 - in:  0 / out:  0
Scraping images for id "n03207743" : dishrag []
 - in:  0 / out:  0
Scraping images for id "n03207941" : dishwasher []
 - in:  0 / out:  0
Scraping images for id "n03208938" : disk_brake []
 - in:  0 / out:  0
Scraping images for id "n03216828" : dock []
 - in:  0 / out:  0
Scraping images for id "n03218198" : dogsled []
 - in:  0 / out:  0
Scraping images for id "n03220513" : dome []
 - in:  0 / out:  0
Scraping images for id "n03223299" : doormat []
 - in:  0 / out:  0
Scraping images for id "n03240683" : drilling_platform []
 - in:  0 / out:  0
Scraping images for id "n03249569" : drum []
 - in:  0 / out:  0
Scraping images for id "n03250847" : drumstick []
 - in:  0 / out:  0
Scraping images for id "n03255030" : dumbbell []
 - in:  0 / out:  0
Scraping images for id "n03259280" : dutch_oven []
 - in:  0 / out:  0
Scraping images for id "n03271574" : electric_fan []
 - in:  0 / out:  0
Scraping images for id "n03272010" : electric_guitar []
 - in:  0 / out:  0
Scraping images for id "n03272562" : electric_locomotive []
 - in:  0 / out:  0
Scraping images for id "n03290653" : entertainment_center []
 - in:  0 / out:  0
Scraping images for id "n03291819" : envelope []
 - in:  0 / out:  0
Scraping images for id "n03297495" : espresso_maker []
 - in:  0 / out:  0
Scraping images for id "n03314780" : face_powder []
 - in:  0 / out:  0
Scraping images for id "n03325584" : feather_boa []
 - in:  0 / out:  0
Scraping images for id "n03337140" : file []
 - in:  0 / out:  0
Scraping images for id "n03344393" : fireboat []
 - in:  0 / out:  0
Scraping images for id "n03345487" : fire_engine []
 - in:  0 / out:  0
Scraping images for id "n03347037" : fire_screen []
 - in:  0 / out:  0
Scraping images for id "n03355925" : flagpole []
 - in:  0 / out:  0
Scraping images for id "n03372029" : flute []
 - in:  0 / out:  0
Scraping images for id "n03376595" : folding_chair []
 - in:  0 / out:  0
Scraping images for id "n03379051" : football_helmet []
 - in:  0 / out:  0
Scraping images for id "n03384352" : forklift []
 - in:  0 / out:  0
Scraping images for id "n03388043" : fountain []
 - in:  0 / out:  0
Scraping images for id "n03388183" : fountain_pen []
 - in:  0 / out:  0
Scraping images for id "n03388549" : four-poster []
 - in:  0 / out:  0
Scraping images for id "n03393912" : freight_car []
 - in:  0 / out:  0
Scraping images for id "n03394916" : french_horn []
 - in:  0 / out:  0
Scraping images for id "n03400231" : frying_pan []
 - in:  0 / out:  0
Scraping images for id "n03404251" : fur_coat []
 - in:  0 / out:  0
Scraping images for id "n03417042" : garbage_truck []
 - in:  0 / out:  0
Scraping images for id "n03424325" : gasmask []
 - in:  0 / out:  0
Scraping images for id "n03425413" : gas_pump []
 - in:  0 / out:  0
Scraping images for id "n03443371" : goblet []
 - in:  0 / out:  0
Scraping images for id "n03444034" : go-kart []
 - in:  0 / out:  0
Scraping images for id "n03445777" : golf_ball []
 - in:  0 / out:  0
Scraping images for id "n03445924" : golfcart []
 - in:  0 / out:  0
Scraping images for id "n03447447" : gondola []
 - in:  0 / out:  0
Scraping images for id "n03447721" : gong []
 - in:  0 / out:  0
Scraping images for id "n03450230" : gown []
 - in:  0 / out:  0
Scraping images for id "n03452741" : grand_piano []
 - in:  0 / out:  0
Scraping images for id "n03457902" : greenhouse []
 - in:  0 / out:  0
Scraping images for id "n03459775" : grille []
 - in:  0 / out:  0
Scraping images for id "n03461385" : grocery_store []
 - in:  0 / out:  0
Scraping images for id "n03467068" : guillotine []
 - in:  0 / out:  0
Scraping images for id "n03476684" : hair_slide []
 - in:  0 / out:  0
Scraping images for id "n03476991" : hair_spray []
 - in:  0 / out:  0
Scraping images for id "n03478589" : half_track []
 - in:  0 / out:  0
Scraping images for id "n03481172" : hammer []
 - in:  0 / out:  0
Scraping images for id "n03482405" : hamper []
 - in:  0 / out:  0
Scraping images for id "n03483316" : hand_blower []
 - in:  0 / out:  0
Scraping images for id "n03485407" : hand-held_computer []
 - in:  0 / out:  0
Scraping images for id "n03485794" : handkerchief []
 - in:  0 / out:  0
Scraping images for id "n03492542" : hard_disc []
 - in:  0 / out:  0
Scraping images for id "n03494278" : harmonica []
 - in:  0 / out:  0
Scraping images for id "n03495258" : harp []
 - in:  0 / out:  0
Scraping images for id "n03496892" : harvester []
 - in:  0 / out:  0
Scraping images for id "n03498962" : hatchet []
 - in:  0 / out:  0
Scraping images for id "n03527444" : holster []
 - in:  0 / out:  0
Scraping images for id "n03529860" : home_theater

[]
 - in:  0 / out:  0
Scraping images for id "n03530642" : honeycomb []
 - in:  0 / out:  0
Scraping images for id "n03532672" : hook []
 - in:  0 / out:  0
Scraping images for id "n03534580" : hoopskirt []
 - in:  0 / out:  0
Scraping images for id "n03535780" : horizontal_bar []
 - in:  0 / out:  0
Scraping images for id "n03538406" : horse_cart []
 - in:  0 / out:  0
Scraping images for id "n03544143" : hourglass []
 - in:  0 / out:  0
Scraping images for id "n03584254" : ipod []
 - in:  0 / out:  0
Scraping images for id "n03584829" : iron []
 - in:  0 / out:  0
Scraping images for id "n03590841" : jack-o'-lantern []
 - in:  0 / out:  0
Scraping images for id "n03594734" : jean []
 - in:  0 / out:  0
Scraping images for id "n03594945" : jeep []
 - in:  0 / out:  0
Scraping images for id "n03595614" : jersey []
 - in:  0 / out:  0
Scraping images for id "n03598930" : jigsaw_puzzle []
 - in:  0 / out:  0
Scraping images for id "n03599486" : jinrikisha []
 - in:  0 / out:  0
Scraping images for id "n03602883" : joystick []
 - in:  0 / out:  0
Scraping images for id "n03617480" : kimono []
 - in:  0 / out:  0
Scraping images for id "n03623198" : knee_pad []
 - in:  0 / out:  0
Scraping images for id "n03627232" : knot []
 - in:  0 / out:  0
Scraping images for id "n03630383" : lab_coat []
 - in:  0 / out:  0
Scraping images for id "n03633091" : ladle []
 - in:  0 / out:  0
Scraping images for id "n03637318" : lampshade []
 - in:  0 / out:  0
Scraping images for id "n03642806" : laptop []
 - in:  0 / out:  0
Scraping images for id "n03649909" : lawn_mower []
 - in:  0 / out:  0
Scraping images for id "n03657121" : lens_cap []
 - in:  0 / out:  0
Scraping images for id "n03658185" : letter_opener []
 - in:  0 / out:  0
Scraping images for id "n03661043" : library []
 - in:  0 / out:  0
Scraping images for id "n03662601" : lifeboat []
 - in:  0 / out:  0
Scraping images for id "n03666591" : lighter []
 - in:  0 / out:  0
Scraping images for id "n03670208" : limousine []
 - in:  0 / out:  0
Scraping images for id "n03673027" : liner []
 - in:  0 / out:  0
Scraping images for id "n03676483" : lipstick []
 - in:  0 / out:  0
Scraping images for id "n03680355" : loafer []
 - in:  0 / out:  0
Scraping images for id "n03690938" : lotion []
 - in:  0 / out:  0
Scraping images for id "n03691459" : loudspeaker []
 - in:  0 / out:  0
Scraping images for id "n03692522" : loupe []
 - in:  0 / out:  0
Scraping images for id "n03697007" : lumbermill []
 - in:  0 / out:  0
Scraping images for id "n03706229" : magnetic_compass []
 - in:  0 / out:  0
Scraping images for id "n03709823" : mailbag []
 - in:  0 / out:  0
Scraping images for id "n03710193" : mailbox []
 - in:  0 / out:  0
Scraping images for id "n03710637" : maillot []
 - in:  0 / out:  0
Scraping images for id "n03710721" : maillot []
 - in:  0 / out:  0
Scraping images for id "n03717622" : manhole_cover []
 - in:  0 / out:  0
Scraping images for id "n03720891" : maraca []
 - in:  0 / out:  0
Scraping images for id "n03721384" : marimba []
 - in:  0 / out:  0
Scraping images for id "n03724870" : mask []
 - in:  0 / out:  0
Scraping images for id "n03729826" : matchstick []
 - in:  0 / out:  0
Scraping images for id "n03733131" : maypole []
 - in:  0 / out:  0
Scraping images for id "n03733281" : maze []
 - in:  0 / out:  0
Scraping images for id "n03733805" : measuring_cup []
 - in:  0 / out:  0
Scraping images for id "n03742115" : medicine_chest []
 - in:  0 / out:  0
Scraping images for id "n03743016" : megalith []
 - in:  0 / out:  0
Scraping images for id "n03759954" : microphone []
 - in:  0 / out:  0
Scraping images for id "n03761084" : microwave []
 - in:  0 / out:  0
Scraping images for id "n03763968" : military_uniform []
 - in:  0 / out:  0
Scraping images for id "n03764736" : milk_can []
 - in:  0 / out:  0
Scraping images for id "n03769881" : minibus []
 - in:  0 / out:  0
Scraping images for id "n03770439" : miniskirt []
 - in:  0 / out:  0
Scraping images for id "n03770679" : minivan []
 - in:  0 / out:  0
Scraping images for id "n03773504" : missile []
 - in:  0 / out:  0
Scraping images for id "n03775071" : mitten []
 - in:  0 / out:  0
Scraping images for id "n03775546" : mixing_bowl []
 - in:  0 / out:  0
Scraping images for id "n03776460" : mobile_home []
 - in:  0 / out:  0
Scraping images for id "n03777568" : model_t []
 - in:  0 / out:  0
Scraping images for id "n03777754" : modem []
 - in:  0 / out:  0
Scraping images for id "n03781244" : monastery []
 - in:  0 / out:  0
Scraping images for id "n03782006" : monitor []
 - in:  0 / out:  0
Scraping images for id "n03785016" : moped []
 - in:  0 / out:  0
Scraping images for id "n03786901" : mortar []
 - in:  0 / out:  0
Scraping images for id "n03787032" : mortarboard []
 - in:  0 / out:  0
Scraping images for id "n03788195" : mosque []
 - in:  0 / out:  0
Scraping images for id "n03788365" : mosquito_net []
 - in:  0 / out:  0
Scraping images for id "n03791053" : motor_scooter []
 - in:  0 / out:  0
Scraping images for id "n03792782" : mountain_bike []
 - in:  0 / out:  0
Scraping images for id "n03792972" : mountain_tent []
 - in:  0 / out:  0
Scraping images for id "n03793489" : mouse []
 - in:  0 / out:  0
Scraping images for id "n03794056" : mousetrap []
 - in:  0 / out:  0
Scraping images for id "n03796401" : moving_van []

 - in:  0 / out:  0
Scraping images for id "n03803284" : muzzle []
 - in:  0 / out:  0
Scraping images for id "n03804744" : nail []
 - in:  0 / out:  0
Scraping images for id "n03814639" : neck_brace []
 - in:  0 / out:  0
Scraping images for id "n03814906" : necklace []
 - in:  0 / out:  0
Scraping images for id "n03825788" : nipple []
 - in:  0 / out:  0
Scraping images for id "n03832673" : notebook []
 - in:  0 / out:  0
Scraping images for id "n03837869" : obelisk []
 - in:  0 / out:  0
Scraping images for id "n03838899" : oboe []
 - in:  0 / out:  0
Scraping images for id "n03840681" : ocarina []
 - in:  0 / out:  0
Scraping images for id "n03841143" : odometer []
 - in:  0 / out:  0
Scraping images for id "n03843555" : oil_filter []
 - in:  0 / out:  0
Scraping images for id "n03854065" : organ []
 - in:  0 / out:  0
Scraping images for id "n03857828" : oscilloscope []
 - in:  0 / out:  0
Scraping images for id "n03866082" : overskirt []
 - in:  0 / out:  0
Scraping images for id "n03868242" : oxcart []
 - in:  0 / out:  0
Scraping images for id "n03868863" : oxygen_mask []
 - in:  0 / out:  0
Scraping images for id "n03871628" : packet []
 - in:  0 / out:  0
Scraping images for id "n03873416" : paddle []
 - in:  0 / out:  0
Scraping images for id "n03874293" : paddlewheel []
 - in:  0 / out:  0
Scraping images for id "n03874599" : padlock []
 - in:  0 / out:  0
Scraping images for id "n03876231" : paintbrush []
 - in:  0 / out:  0
Scraping images for id "n03877472" : pajama []
 - in:  0 / out:  0
Scraping images for id "n03877845" : palace []
 - in:  0 / out:  0
Scraping images for id "n03884397" : panpipe []
 - in:  0 / out:  0
Scraping images for id "n03887697" : paper_towel []
 - in:  0 / out:  0
Scraping images for id "n03888257" : parachute []
 - in:  0 / out:  0
Scraping images for id "n03888605" : parallel_bars []
 - in:  0 / out:  0
Scraping images for id "n03891251" : park_bench []
 - in:  0 / out:  0
Scraping images for id "n03891332" : parking_meter []
 - in:  0 / out:  0
Scraping images for id "n03895866" : passenger_car []
 - in:  0 / out:  0
Scraping images for id "n03899768" : patio []
 - in:  0 / out:  0
Scraping images for id "n03902125" : pay-phone []
 - in:  0 / out:  0
Scraping images for id "n03903868" : pedestal []
 - in:  0 / out:  0
Scraping images for id "n03908618" : pencil_box []
 - in:  0 / out:  0
Scraping images for id "n03908714" : pencil_sharpener []
 - in:  0 / out:  0
Scraping images for id "n03916031" : perfume []
 - in:  0 / out:  0
Scraping images for id "n03920288" : petri_dish []
 - in:  0 / out:  0
Scraping images for id "n03924679" : photocopier []
 - in:  0 / out:  0
Scraping images for id "n03929660" : pick []
 - in:  0 / out:  0
Scraping images for id "n03929855" : pickelhaube []
 - in:  0 / out:  0
Scraping images for id "n03930313" : picket_fence []
 - in:  0 / out:  0
Scraping images for id "n03930630" : pickup []
 - in:  0 / out:  0
Scraping images for id "n03933933" : pier []
 - in:  0 / out:  0
Scraping images for id "n03935335" : piggy_bank []
 - in:  0 / out:  0
Scraping images for id "n03937543" : pill_bottle []
 - in:  0 / out:  0
Scraping images for id "n03938244" : pillow []
 - in:  0 / out:  0
Scraping images for id "n03942813" : ping-pong_ball []
 - in:  0 / out:  0
Scraping images for id "n03944341" : pinwheel []
 - in:  0 / out:  0
Scraping images for id "n03947888" : pirate []
 - in:  0 / out:  0
Scraping images for id "n03950228" : pitcher []
 - in:  0 / out:  0
Scraping images for id "n03954731" : plane []
 - in:  0 / out:  0
Scraping images for id "n03956157" : planetarium []
 - in:  0 / out:  0
Scraping images for id "n03958227" : plastic_bag []
 - in:  0 / out:  0
Scraping images for id "n03961711" : plate_rack []
 - in:  0 / out:  0
Scraping images for id "n03967562" : plow []
 - in:  0 / out:  0
Scraping images for id "n03970156" : plunger []
 - in:  0 / out:  0
Scraping images for id "n03976467" : polaroid_camera []
 - in:  0 / out:  0
Scraping images for id "n03976657" : pole []
 - in:  0 / out:  0
Scraping images for id "n03977966" : police_van []
 - in:  0 / out:  0
Scraping images for id "n03980874" : poncho []
 - in:  0 / out:  0
Scraping images for id "n03982430" : pool_table []
 - in:  0 / out:  0
Scraping images for id "n03983396" : pop_bottle []
 - in:  0 / out:  0
Scraping images for id "n03991062" : pot []
 - in:  0 / out:  0
Scraping images for id "n03992509" : potter's_wheel []
 - in:  0 / out:  0
Scraping images for id "n03995372" : power_drill []
 - in:  0 / out:  0
Scraping images for id "n03998194" : prayer_rug []
 - in:  0 / out:  0
Scraping images for id "n04004767" : printer []
 - in:  0 / out:  0
Scraping images for id "n04005630" : prison []
 - in:  0 / out:  0
Scraping images for id "n04008634" : projectile []
 - in:  0 / out:  0
Scraping images for id "n04009552" : projector []
 - in:  0 / out:  0
Scraping images for id "n04019541" : puck []
 - in:  0 / out:  0
Scraping images for id "n04023962" : punching_bag []
 - in:  0 / out:  0
Scraping images for id "n04026417" : purse []
 - in:  0 / out:  0
Scraping images for id "n04033901" : quill []
 - in:  0 / out:  0
Scraping images for id "n04033995" : quilt []
 - in:  0 / out:  0
Scraping images for id "n04037443" : racer []
 - in:  0 / out:  0
Scraping images for id "n04039381" : racket []
 - in:  0 / out:  0
Scraping images for id "n04040759" : radiator []
 - in:  0 / out:  0
Scraping images for id "n04041544" : radio []
 - in:  0 / out:  0
Scraping images for id "n04044716" : radio_telescope []
 - in:  0 / out:  0
Scraping images for id "n04049303" : rain_barrel []

 - in:  0 / out:  0
Scraping images for id "n04065272" : recreational_vehicle []
 - in:  0 / out:  0
Scraping images for id "n04067472" : reel []
 - in:  0 / out:  0
Scraping images for id "n04069434" : reflex_camera []
 - in:  0 / out:  0
Scraping images for id "n04070727" : refrigerator []
 - in:  0 / out:  0
Scraping images for id "n04074963" : remote_control []
 - in:  0 / out:  0
Scraping images for id "n04081281" : restaurant []
 - in:  0 / out:  0
Scraping images for id "n04086273" : revolver []
 - in:  0 / out:  0
Scraping images for id "n04090263" : rifle []
 - in:  0 / out:  0
Scraping images for id "n04099969" : rocking_chair []
 - in:  0 / out:  0
Scraping images for id "n04111531" : rotisserie []
 - in:  0 / out:  0
Scraping images for id "n04116512" : rubber_eraser []
 - in:  0 / out:  0
Scraping images for id "n04118538" : rugby_ball []
 - in:  0 / out:  0
Scraping images for id "n04118776" : rule []
 - in:  0 / out:  0
Scraping images for id "n04120489" : running_shoe []
 - in:  0 / out:  0
Scraping images for id "n04125021" : safe []
 - in:  0 / out:  0
Scraping images for id "n04127249" : safety_pin []
 - in:  0 / out:  0
Scraping images for id "n04131690" : saltshaker []
 - in:  0 / out:  0
Scraping images for id "n04133789" : sandal []
 - in:  0 / out:  0
Scraping images for id "n04136333" : sarong []
 - in:  0 / out:  0
Scraping images for id "n04141076" : sax []
 - in:  0 / out:  0
Scraping images for id "n04141327" : scabbard []
 - in:  0 / out:  0
Scraping images for id "n04141975" : scale []
 - in:  0 / out:  0
Scraping images for id "n04146614" : school_bus []
 - in:  0 / out:  0
Scraping images for id "n04147183" : schooner []
 - in:  0 / out:  0
Scraping images for id "n04149813" : scoreboard []
 - in:  0 / out:  0
Scraping images for id "n04152593" : screen []
 - in:  0 / out:  0
Scraping images for id "n04153751" : screw []
 - in:  0 / out:  0
Scraping images for id "n04154565" : screwdriver []
 - in:  0 / out:  0
Scraping images for id "n04162706" : seat_belt []
 - in:  0 / out:  0
Scraping images for id "n04179913" : sewing_machine []
 - in:  0 / out:  0
Scraping images for id "n04192698" : shield []
 - in:  0 / out:  0
Scraping images for id "n04200800" : shoe_shop []
 - in:  0 / out:  0
Scraping images for id "n04201297" : shoji []
 - in:  0 / out:  0
Scraping images for id "n04204238" : shopping_basket []
 - in:  0 / out:  0
Scraping images for id "n04204347" : shopping_cart []
 - in:  0 / out:  0
Scraping images for id "n04208210" : shovel []
 - in:  0 / out:  0
Scraping images for id "n04209133" : shower_cap []
 - in:  0 / out:  0
Scraping images for id "n04209239" : shower_curtain []
 - in:  0 / out:  0
Scraping images for id "n04228054" : ski []
 - in:  0 / out:  0
Scraping images for id "n04229816" : ski_mask []
 - in:  0 / out:  0
Scraping images for id "n04235860" : sleeping_bag []
 - in:  0 / out:  0
Scraping images for id "n04238763" : slide_rule []
 - in:  0 / out:  0
Scraping images for id "n04239074" : sliding_door []
 - in:  0 / out:  0
Scraping images for id "n04243546" : slot []
 - in:  0 / out:  0
Scraping images for id "n04251144" : snorkel []
 - in:  0 / out:  0
Scraping images for id "n04252077" : snowmobile []
 - in:  0 / out:  0
Scraping images for id "n04252225" : snowplow []
 - in:  0 / out:  0
Scraping images for id "n04254120" : soap_dispenser []
 - in:  0 / out:  0
Scraping images for id "n04254680" : soccer_ball []
 - in:  0 / out:  0
Scraping images for id "n04254777" : sock []
 - in:  0 / out:  0
Scraping images for id "n04258138" : solar_dish []
 - in:  0 / out:  0
Scraping images for id "n04259630" : sombrero []
 - in:  0 / out:  0
Scraping images for id "n04263257" : soup_bowl []
 - in:  0 / out:  0
Scraping images for id "n04264628" : space_bar []
 - in:  0 / out:  0
Scraping images for id "n04265275" : space_heater []
 - in:  0 / out:  0
Scraping images for id "n04266014" : space_shuttle []
 - in:  0 / out:  0
Scraping images for id "n04270147" : spatula []
 - in:  0 / out:  0
Scraping images for id "n04273569" : speedboat []
 - in:  0 / out:  0
Scraping images for id "n04275548" : spider_web []
 - in:  0 / out:  0
Scraping images for id "n04277352" : spindle []
 - in:  0 / out:  0
Scraping images for id "n04285008" : sports_car []
 - in:  0 / out:  0
Scraping images for id "n04286575" : spotlight []
 - in:  0 / out:  0
Scraping images for id "n04296562" : stage []
 - in:  0 / out:  0
Scraping images for id "n04310018" : steam_locomotive []
 - in:  0 / out:  0
Scraping images for id "n04311004" : steel_arch_bridge []
 - in:  0 / out:  0
Scraping images for id "n04311174" : steel_drum []
 - in:  0 / out:  0
Scraping images for id "n04317175" : stethoscope []
 - in:  0 / out:  0
Scraping images for id "n04325704" : stole []
 - in:  0 / out:  0
Scraping images for id "n04326547" : stone_wall []
 - in:  0 / out:  0
Scraping images for id "n04328186" : stopwatch []
 - in:  0 / out:  0
Scraping images for id "n04330267" : stove []
 - in:  0 / out:  0
Scraping images for id "n04332243" : strainer []
 - in:  0 / out:  0
Scraping images for id "n04335435" : streetcar []
 - in:  0 / out:  0
Scraping images for id "n04336792" : stretcher []
 - in:  0 / out:  0
Scraping images for id "n04344873" : studio_couch []
 - in:  0 / out:  0
Scraping images for id "n04346328" : stupa []
 - in:  0 / out:  0
Scraping images for id "n04347754" : submarine []
 - in:  0 / out:  0
Scraping images for id "n04350905" : suit []
 - in:  0 / out:  0
Scraping images for id "n04355338" : sundial []
 - in:  0 / out:  0
Scraping images for id "n04355933" : sunglass []
 - in:  0 / out:  0
Scraping images for id "n04356056" : sunglasses []

 - in:  0 / out:  0
Scraping images for id "n04357314" : sunscreen []
 - in:  0 / out:  0
Scraping images for id "n04366367" : suspension_bridge []
 - in:  0 / out:  0
Scraping images for id "n04367480" : swab []
 - in:  0 / out:  0
Scraping images for id "n04370456" : sweatshirt []
 - in:  0 / out:  0
Scraping images for id "n04371430" : swimming_trunks []
 - in:  0 / out:  0
Scraping images for id "n04371774" : swing []
 - in:  0 / out:  0
Scraping images for id "n04372370" : switch []
 - in:  0 / out:  0
Scraping images for id "n04376876" : syringe []
 - in:  0 / out:  0
Scraping images for id "n04380533" : table_lamp []
 - in:  0 / out:  0
Scraping images for id "n04389033" : tank []
 - in:  0 / out:  0
Scraping images for id "n04392985" : tape_player []
 - in:  0 / out:  0
Scraping images for id "n04398044" : teapot []
 - in:  0 / out:  0
Scraping images for id "n04399382" : teddy []
 - in:  0 / out:  0
Scraping images for id "n04404412" : television []
 - in:  0 / out:  0
Scraping images for id "n04409515" : tennis_ball []
 - in:  0 / out:  0
Scraping images for id "n04417672" : thatch []
 - in:  0 / out:  0
Scraping images for id "n04418357" : theater_curtain []
 - in:  0 / out:  0
Scraping images for id "n04423845" : thimble []
 - in:  0 / out:  0
Scraping images for id "n04428191" : thresher []
 - in:  0 / out:  0
Scraping images for id "n04429376" : throne []
 - in:  0 / out:  0
Scraping images for id "n04435653" : tile_roof []
 - in:  0 / out:  0
Scraping images for id "n04442312" : toaster []
 - in:  0 / out:  0
Scraping images for id "n04443257" : tobacco_shop []
 - in:  0 / out:  0
Scraping images for id "n04447861" : toilet_seat []
 - in:  0 / out:  0
Scraping images for id "n04456115" : torch []
 - in:  0 / out:  0
Scraping images for id "n04458633" : totem_pole []
 - in:  0 / out:  0
Scraping images for id "n04461696" : tow_truck []
 - in:  0 / out:  0
Scraping images for id "n04462240" : toyshop []
 - in:  0 / out:  0
Scraping images for id "n04465501" : tractor []
 - in:  0 / out:  0
Scraping images for id "n04467665" : trailer_truck []
 - in:  0 / out:  0
Scraping images for id "n04476259" : tray []
 - in:  0 / out:  0
Scraping images for id "n04479046" : trench_coat []
 - in:  0 / out:  0
Scraping images for id "n04482393" : tricycle []
 - in:  0 / out:  0
Scraping images for id "n04483307" : trimaran []
 - in:  0 / out:  0
Scraping images for id "n04485082" : tripod []
 - in:  0 / out:  0
Scraping images for id "n04486054" : triumphal_arch []
 - in:  0 / out:  0
Scraping images for id "n04487081" : trolleybus []
 - in:  0 / out:  0
Scraping images for id "n04487394" : trombone []
 - in:  0 / out:  0
Scraping images for id "n04493381" : tub []
 - in:  0 / out:  0
Scraping images for id "n04501370" : turnstile []
 - in:  0 / out:  0
Scraping images for id "n04505470" : typewriter_keyboard []
 - in:  0 / out:  0
Scraping images for id "n04507155" : umbrella []
 - in:  0 / out:  0
Scraping images for id "n04509417" : unicycle []
 - in:  0 / out:  0
Scraping images for id "n04515003" : upright []
 - in:  0 / out:  0
Scraping images for id "n04517823" : vacuum []
 - in:  0 / out:  0
Scraping images for id "n04522168" : vase []
 - in:  0 / out:  0
Scraping images for id "n04523525" : vault []
 - in:  0 / out:  0
Scraping images for id "n04525038" : velvet []
 - in:  0 / out:  0
Scraping images for id "n04525305" : vending_machine []
 - in:  0 / out:  0
Scraping images for id "n04532106" : vestment []
 - in:  0 / out:  0
Scraping images for id "n04532670" : viaduct []
 - in:  0 / out:  0
Scraping images for id "n04536866" : violin []
 - in:  0 / out:  0
Scraping images for id "n04540053" : volleyball []
 - in:  0 / out:  0
Scraping images for id "n04542943" : waffle_iron []
 - in:  0 / out:  0
Scraping images for id "n04548280" : wall_clock []
 - in:  0 / out:  0
Scraping images for id "n04548362" : wallet []
 - in:  0 / out:  0
Scraping images for id "n04550184" : wardrobe []
 - in:  0 / out:  0
Scraping images for id "n04552348" : warplane []
 - in:  0 / out:  0
Scraping images for id "n04553703" : washbasin []
 - in:  0 / out:  0
Scraping images for id "n04554684" : washer []
 - in:  0 / out:  0
Scraping images for id "n04557648" : water_bottle []
 - in:  0 / out:  0
Scraping images for id "n04560804" : water_jug []
 - in:  0 / out:  0
Scraping images for id "n04562935" : water_tower []
 - in:  0 / out:  0
Scraping images for id "n04579145" : whiskey_jug []
 - in:  0 / out:  0
Scraping images for id "n04579432" : whistle []
 - in:  0 / out:  0
Scraping images for id "n04584207" : wig []
 - in:  0 / out:  0
Scraping images for id "n04589890" : window_screen []
 - in:  0 / out:  0
Scraping images for id "n04590129" : window_shade []
 - in:  0 / out:  0
Scraping images for id "n04591157" : windsor_tie []
 - in:  0 / out:  0
Scraping images for id "n04591713" : wine_bottle []
 - in:  0 / out:  0
Scraping images for id "n04592741" : wing []
 - in:  0 / out:  0
Scraping images for id "n04596742" : wok []
 - in:  0 / out:  0
Scraping images for id "n04597913" : wooden_spoon []
 - in:  0 / out:  0
Scraping images for id "n04599235" : wool []
 - in:  0 / out:  0
Scraping images for id "n04604644" : worm_fence []
 - in:  0 / out:  0
Scraping images for id "n04606251" : wreck []

 - in:  0 / out:  0
Scraping images for id "n04612504" : yawl []
 - in:  0 / out:  0
Scraping images for id "n04613696" : yurt []
 - in:  0 / out:  0
Scraping images for id "n06359193" : web_site []
 - in:  0 / out:  0
Scraping images for id "n06596364" : comic_book []
 - in:  0 / out:  0
Scraping images for id "n06785654" : crossword_puzzle []
 - in:  0 / out:  0
Scraping images for id "n06794110" : street_sign []
 - in:  0 / out:  0
Scraping images for id "n06874185" : traffic_light []
 - in:  0 / out:  0
Scraping images for id "n07248320" : book_jacket []
 - in:  0 / out:  0
Scraping images for id "n07565083" : menu []
 - in:  0 / out:  0
Scraping images for id "n07579787" : plate []
 - in:  0 / out:  0
Scraping images for id "n07583066" : guacamole []
 - in:  0 / out:  0
Scraping images for id "n07584110" : consomme []
 - in:  0 / out:  0
Scraping images for id "n07590611" : hot_pot []
 - in:  0 / out:  0
Scraping images for id "n07613480" : trifle []
 - in:  0 / out:  0
Scraping images for id "n07614500" : ice_cream []
 - in:  0 / out:  0
Scraping images for id "n07615774" : ice_lolly []
 - in:  0 / out:  0
Scraping images for id "n07684084" : french_loaf []
 - in:  0 / out:  0
Scraping images for id "n07693725" : bagel []
 - in:  0 / out:  0
Scraping images for id "n07695742" : pretzel []
 - in:  0 / out:  0
Scraping images for id "n07697313" : cheeseburger []
 - in:  0 / out:  0
Scraping images for id "n07697537" : hotdog []
 - in:  0 / out:  0
Scraping images for id "n07711569" : mashed_potato []
 - in:  0 / out:  0
Scraping images for id "n07714571" : head_cabbage []
 - in:  0 / out:  0
Scraping images for id "n07714990" : broccoli []
 - in:  0 / out:  0
Scraping images for id "n07715103" : cauliflower []
 - in:  0 / out:  0
Scraping images for id "n07716358" : zucchini []
 - in:  0 / out:  0
Scraping images for id "n07716906" : spaghetti_squash []
 - in:  0 / out:  0
Scraping images for id "n07717410" : acorn_squash []
 - in:  0 / out:  0
Scraping images for id "n07717556" : butternut_squash []
 - in:  0 / out:  0
Scraping images for id "n07718472" : cucumber []
 - in:  0 / out:  0
Scraping images for id "n07718747" : artichoke []
 - in:  0 / out:  0
Scraping images for id "n07720875" : bell_pepper []
 - in:  0 / out:  0
Scraping images for id "n07730033" : cardoon []
 - in:  0 / out:  0
Scraping images for id "n07734744" : mushroom []
 - in:  0 / out:  0
Scraping images for id "n07742313" : granny_smith []
 - in:  0 / out:  0
Scraping images for id "n07745940" : strawberry []
 - in:  0 / out:  0
Scraping images for id "n07747607" : orange []
 - in:  0 / out:  0
Scraping images for id "n07749582" : lemon []
 - in:  0 / out:  0
Scraping images for id "n07753113" : fig []
 - in:  0 / out:  0
Scraping images for id "n07753275" : pineapple []
 - in:  0 / out:  0
Scraping images for id "n07753592" : banana []
 - in:  0 / out:  0
Scraping images for id "n07754684" : jackfruit []
 - in:  0 / out:  0
Scraping images for id "n07760859" : custard_apple []
 - in:  0 / out:  0
Scraping images for id "n07768694" : pomegranate []
 - in:  0 / out:  0
Scraping images for id "n07802026" : hay []
 - in:  0 / out:  0
Scraping images for id "n07831146" : carbonara []
 - in:  0 / out:  0
Scraping images for id "n07836838" : chocolate_sauce []
 - in:  0 / out:  0
Scraping images for id "n07860988" : dough []
 - in:  0 / out:  0
Scraping images for id "n07871810" : meat_loaf []
 - in:  0 / out:  0
Scraping images for id "n07873807" : pizza []
 - in:  0 / out:  0
Scraping images for id "n07875152" : potpie []
 - in:  0 / out:  0
Scraping images for id "n07880968" : burrito []
 - in:  0 / out:  0
Scraping images for id "n07892512" : red_wine []
 - in:  0 / out:  0
Scraping images for id "n07920052" : espresso []
 - in:  0 / out:  0
Scraping images for id "n07930864" : cup []
 - in:  0 / out:  0
Scraping images for id "n07932039" : eggnog []
 - in:  0 / out:  0
Scraping images for id "n09193705" : alp []
 - in:  0 / out:  0
Scraping images for id "n09229709" : bubble []
 - in:  0 / out:  0
Scraping images for id "n09246464" : cliff []
 - in:  0 / out:  0
Scraping images for id "n09256479" : coral_reef []
 - in:  0 / out:  0
Scraping images for id "n09288635" : geyser []
 - in:  0 / out:  0
Scraping images for id "n09332890" : lakeside []
 - in:  0 / out:  0
Scraping images for id "n09399592" : promontory []
 - in:  0 / out:  0
Scraping images for id "n09421951" : sandbar []
 - in:  0 / out:  0
Scraping images for id "n09428293" : seashore []
 - in:  0 / out:  0
Scraping images for id "n09468604" : valley []
 - in:  0 / out:  0
Scraping images for id "n09472597" : volcano []
 - in:  0 / out:  0
Scraping images for id "n09835506" : ballplayer []
 - in:  0 / out:  0
Scraping images for id "n10148035" : groom []
 - in:  0 / out:  0
Scraping images for id "n10565667" : scuba_diver []
 - in:  0 / out:  0
Scraping images for id "n11879895" : rapeseed []
 - in:  0 / out:  0
Scraping images for id "n11939491" : daisy []
 - in:  0 / out:  0
Scraping images for id "n12057211" : yellow_lady's_slipper []
 - in:  0 / out:  0
Scraping images for id "n12144580" : corn

[]
 - in:  0 / out:  0
Scraping images for id "n12267677" : acorn []
 - in:  0 / out:  0
Scraping images for id "n12620546" : hip []
 - in:  0 / out:  0
Scraping images for id "n12768682" : buckeye []
 - in:  0 / out:  0
Scraping images for id "n12985857" : coral_fungus []
 - in:  0 / out:  0
Scraping images for id "n12998815" : agaric []
 - in:  0 / out:  0
Scraping images for id "n13037406" : gyromitra []
 - in:  0 / out:  0
Scraping images for id "n13040303" : stinkhorn []
 - in:  0 / out:  0
Scraping images for id "n13044778" : earthstar []
 - in:  0 / out:  0
Scraping images for id "n13052670" : hen-of-the-woods []
 - in:  0 / out:  0
Scraping images for id "n13054560" : bolete []
 - in:  0 / out:  0
Scraping images for id "n13133613" : ear []
 - in:  0 / out:  0
Scraping images for id "n15075141" : toilet_tissue []
 - in:  0 / out:  0

Folder "train"

Scraping images for id "n01440764" : tench []
 - in:  0 / out:  0
Scraping images for id "n01443537" : goldfish []
 - in:  0 / out:  0
Scraping images for id "n01484850" : great_white_shark []
 - in:  0 / out:  0
Scraping images for id "n01491361" : tiger_shark []
 - in:  0 / out:  0
Scraping images for id "n01494475" : hammerhead []
 - in:  0 / out:  0
Scraping images for id "n01496331" : electric_ray []
 - in:  0 / out:  0
Scraping images for id "n01498041" : stingray []
 - in:  0 / out:  0
Scraping images for id "n01514668" : cock []
 - in:  0 / out:  0
Scraping images for id "n01514859" : hen []
 - in:  0 / out:  0
Scraping images for id "n01518878" : ostrich []
 - in:  0 / out:  0
Scraping images for id "n01530575" : brambling []
 - in:  0 / out:  0
Scraping images for id "n01531178" : goldfinch []
 - in:  0 / out:  0
Scraping images for id "n01532829" : house_finch []
 - in:  0 / out:  0
Scraping images for id "n01534433" : junco []
 - in:  0 / out:  0
Scraping images for id "n01537544" : indigo_bunting []
 - in:  0 / out:  0
Scraping images for id "n01558993" : robin []
 - in:  0 / out:  0
Scraping images for id "n01560419" : bulbul []
 - in:  0 / out:  0
Scraping images for id "n01580077" : jay []
 - in:  0 / out:  0
Scraping images for id "n01582220" : magpie []
 - in:  0 / out:  0
Scraping images for id "n01592084" : chickadee []
 - in:  0 / out:  0
Scraping images for id "n01601694" : water_ouzel []
 - in:  0 / out:  0
Scraping images for id "n01608432" : kite []
 - in:  0 / out:  0
Scraping images for id "n01614925" : bald_eagle []
 - in:  0 / out:  0
Scraping images for id "n01616318" : vulture []
 - in:  0 / out:  0
Scraping images for id "n01622779" : great_grey_owl []
 - in:  0 / out:  0
Scraping images for id "n01629819" : european_fire_salamander []
 - in:  0 / out:  0
Scraping images for id "n01630670" : common_newt []
 - in:  0 / out:  0
Scraping images for id "n01631663" : eft []
 - in:  0 / out:  0
Scraping images for id "n01632458" : spotted_salamander []
 - in:  0 / out:  0
Scraping images for id "n01632777" : axolotl []
 - in:  0 / out:  0
Scraping images for id "n01641577" : bullfrog []
 - in:  0 / out:  0
Scraping images for id "n01644373" : tree_frog []
 - in:  0 / out:  0
Scraping images for id "n01644900" : tailed_frog []
 - in:  0 / out:  0
Scraping images for id "n01664065" : loggerhead []
 - in:  0 / out:  0
Scraping images for id "n01665541" : leatherback_turtle []
 - in:  0 / out:  0
Scraping images for id "n01667114" : mud_turtle []
 - in:  0 / out:  0
Scraping images for id "n01667778" : terrapin []
 - in:  0 / out:  0
Scraping images for id "n01669191" : box_turtle []
 - in:  0 / out:  0
Scraping images for id "n01675722" : banded_gecko []
 - in:  0 / out:  0
Scraping images for id "n01677366" : common_iguana []
 - in:  0 / out:  0
Scraping images for id "n01682714" : american_chameleon []
 - in:  0 / out:  0
Scraping images for id "n01685808" : whiptail []
 - in:  0 / out:  0
Scraping images for id "n01687978" : agama []
 - in:  0 / out:  0
Scraping images for id "n01688243" : frilled_lizard []
 - in:  0 / out:  0
Scraping images for id "n01689811" : alligator_lizard []
 - in:  0 / out:  0
Scraping images for id "n01692333" : gila_monster []
 - in:  0 / out:  0
Scraping images for id "n01693334" : green_lizard []
 - in:  0 / out:  0
Scraping images for id "n01694178" : african_chameleon []
 - in:  0 / out:  0
Scraping images for id "n01695060" : komodo_dragon []
 - in:  0 / out:  0
Scraping images for id "n01697457" : african_crocodile []
 - in:  0 / out:  0
Scraping images for id "n01698640" : american_alligator []
 - in:  0 / out:  0
Scraping images for id "n01704323" : triceratops []
 - in:  0 / out:  0
Scraping images for id "n01728572" : thunder_snake []
 - in:  0 / out:  0
Scraping images for id "n01728920" : ringneck_snake []
 - in:  0 / out:  0
Scraping images for id "n01729322" : hognose_snake []
 - in:  0 / out:  0
Scraping images for id "n01729977" : green_snake []
 - in:  0 / out:  0
Scraping images for id "n01734418" : king_snake []
 - in:  0 / out:  0
Scraping images for id "n01735189" : garter_snake []
 - in:  0 / out:  0
Scraping images for id "n01737021" : water_snake []
 - in:  0 / out:  0
Scraping images for id "n01739381" : vine_snake []
 - in:  0 / out:  0
Scraping images for id "n01740131" : night_snake []
 - in:  0 / out:  0
Scraping images for id "n01742172" : boa_constrictor []
 - in:  0 / out:  0
Scraping images for id "n01744401" : rock_python []
 - in:  0 / out:  0
Scraping images for id "n01748264" : indian_cobra []
 - in:  0 / out:  0
Scraping images for id "n01749939" : green_mamba []
 - in:  0 / out:  0
Scraping images for id "n01751748" : sea_snake []
 - in:  0 / out:  0
Scraping images for id "n01753488" : horned_viper []
 - in:  0 / out:  0
Scraping images for id "n01755581" : diamondback []
 - in:  0 / out:  0
Scraping images for id "n01756291" : sidewinder []
 - in:  0 / out:  0
Scraping images for id "n01768244" : trilobite []
 - in:  0 / out:  0
Scraping images for id "n01770081" : harvestman []

 - in:  0 / out:  0
Scraping images for id "n01770393" : scorpion []
 - in:  0 / out:  0
Scraping images for id "n01773157" : black_and_gold_garden_spider []
 - in:  0 / out:  0
Scraping images for id "n01773549" : barn_spider []
 - in:  0 / out:  0
Scraping images for id "n01773797" : garden_spider []
 - in:  0 / out:  0
Scraping images for id "n01774384" : black_widow []
 - in:  0 / out:  0
Scraping images for id "n01774750" : tarantula []
 - in:  0 / out:  0
Scraping images for id "n01775062" : wolf_spider []
 - in:  0 / out:  0
Scraping images for id "n01776313" : tick []
 - in:  0 / out:  0
Scraping images for id "n01784675" : centipede []
 - in:  0 / out:  0
Scraping images for id "n01795545" : black_grouse []
 - in:  0 / out:  0
Scraping images for id "n01796340" : ptarmigan []
 - in:  0 / out:  0
Scraping images for id "n01797886" : ruffed_grouse []
 - in:  0 / out:  0
Scraping images for id "n01798484" : prairie_chicken []
 - in:  0 / out:  0
Scraping images for id "n01806143" : peacock []
 - in:  0 / out:  0
Scraping images for id "n01806567" : quail []
 - in:  0 / out:  0
Scraping images for id "n01807496" : partridge []
 - in:  0 / out:  0
Scraping images for id "n01817953" : african_grey []
 - in:  0 / out:  0
Scraping images for id "n01818515" : macaw []
 - in:  0 / out:  0
Scraping images for id "n01819313" : sulphur-crested_cockatoo []
 - in:  0 / out:  0
Scraping images for id "n01820546" : lorikeet []
 - in:  0 / out:  0
Scraping images for id "n01824575" : coucal []
 - in:  0 / out:  0
Scraping images for id "n01828970" : bee_eater []
 - in:  0 / out:  0
Scraping images for id "n01829413" : hornbill []
 - in:  0 / out:  0
Scraping images for id "n01833805" : hummingbird []
 - in:  0 / out:  0
Scraping images for id "n01843065" : jacamar []
 - in:  0 / out:  0
Scraping images for id "n01843383" : toucan []
 - in:  0 / out:  0
Scraping images for id "n01847000" : drake []
 - in:  0 / out:  0
Scraping images for id "n01855032" : red-breasted_merganser []
 - in:  0 / out:  0
Scraping images for id "n01855672" : goose []
 - in:  0 / out:  0
Scraping images for id "n01860187" : black_swan []
 - in:  0 / out:  0
Scraping images for id "n01871265" : tusker []
 - in:  0 / out:  0
Scraping images for id "n01872401" : echidna []
 - in:  0 / out:  0
Scraping images for id "n01873310" : platypus []
 - in:  0 / out:  0
Scraping images for id "n01877812" : wallaby []
 - in:  0 / out:  0
Scraping images for id "n01882714" : koala []
 - in:  0 / out:  0
Scraping images for id "n01883070" : wombat []
 - in:  0 / out:  0
Scraping images for id "n01910747" : jellyfish []
 - in:  0 / out:  0
Scraping images for id "n01914609" : sea_anemone []
 - in:  0 / out:  0
Scraping images for id "n01917289" : brain_coral []
 - in:  0 / out:  0
Scraping images for id "n01924916" : flatworm []
 - in:  0 / out:  0
Scraping images for id "n01930112" : nematode []
 - in:  0 / out:  0
Scraping images for id "n01943899" : conch []
 - in:  0 / out:  0
Scraping images for id "n01944390" : snail []
 - in:  0 / out:  0
Scraping images for id "n01945685" : slug []
 - in:  0 / out:  0
Scraping images for id "n01950731" : sea_slug []
 - in:  0 / out:  0
Scraping images for id "n01955084" : chiton []
 - in:  0 / out:  0
Scraping images for id "n01968897" : chambered_nautilus []
 - in:  0 / out:  0
Scraping images for id "n01978287" : dungeness_crab []
 - in:  0 / out:  0
Scraping images for id "n01978455" : rock_crab []
 - in:  0 / out:  0
Scraping images for id "n01980166" : fiddler_crab []
 - in:  0 / out:  0
Scraping images for id "n01981276" : king_crab []
 - in:  0 / out:  0
Scraping images for id "n01983481" : american_lobster []
 - in:  0 / out:  0
Scraping images for id "n01984695" : spiny_lobster []
 - in:  0 / out:  0
Scraping images for id "n01985128" : crayfish []
 - in:  0 / out:  0
Scraping images for id "n01986214" : hermit_crab []
 - in:  0 / out:  0
Scraping images for id "n01990800" : isopod []
 - in:  0 / out:  0
Scraping images for id "n02002556" : white_stork []
 - in:  0 / out:  0
Scraping images for id "n02002724" : black_stork []
 - in:  0 / out:  0
Scraping images for id "n02006656" : spoonbill []
 - in:  0 / out:  0
Scraping images for id "n02007558" : flamingo []
 - in:  0 / out:  0
Scraping images for id "n02009229" : little_blue_heron []
 - in:  0 / out:  0
Scraping images for id "n02009912" : american_egret []
 - in:  0 / out:  0
Scraping images for id "n02011460" : bittern []
 - in:  0 / out:  0
Scraping images for id "n02012849" : crane []
 - in:  0 / out:  0
Scraping images for id "n02013706" : limpkin []
 - in:  0 / out:  0
Scraping images for id "n02017213" : european_gallinule []
 - in:  0 / out:  0
Scraping images for id "n02018207" : american_coot []
 - in:  0 / out:  0
Scraping images for id "n02018795" : bustard []
 - in:  0 / out:  0
Scraping images for id "n02025239" : ruddy_turnstone []
 - in:  0 / out:  0
Scraping images for id "n02027492" : red-backed_sandpiper []
 - in:  0 / out:  0
Scraping images for id "n02028035" : redshank []
 - in:  0 / out:  0
Scraping images for id "n02033041" : dowitcher []
 - in:  0 / out:  0
Scraping images for id "n02037110" : oystercatcher []
 - in:  0 / out:  0
Scraping images for id "n02051845" : pelican []
 - in:  0 / out:  0
Scraping images for id "n02056570" : king_penguin []
 - in:  0 / out:  0
Scraping images for id "n02058221" : albatross []
 - in:  0 / out:  0
Scraping images for id "n02066245" : grey_whale []
 - in:  0 / out:  0
Scraping images for id "n02071294" : killer_whale []

 - in:  0 / out:  0
Scraping images for id "n02074367" : dugong []
 - in:  0 / out:  0
Scraping images for id "n02077923" : sea_lion []
 - in:  0 / out:  0
Scraping images for id "n02085620" : chihuahua []
 - in:  0 / out:  0
Scraping images for id "n02085782" : japanese_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02085936" : maltese_dog []
 - in:  0 / out:  0
Scraping images for id "n02086079" : pekinese []
 - in:  0 / out:  0
Scraping images for id "n02086240" : shih-tzu []
 - in:  0 / out:  0
Scraping images for id "n02086646" : blenheim_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02086910" : papillon []
 - in:  0 / out:  0
Scraping images for id "n02087046" : toy_terrier []
 - in:  0 / out:  0
Scraping images for id "n02087394" : rhodesian_ridgeback []
 - in:  0 / out:  0
Scraping images for id "n02088094" : afghan_hound []
 - in:  0 / out:  0
Scraping images for id "n02088238" : basset []
 - in:  0 / out:  0
Scraping images for id "n02088364" : beagle []
 - in:  0 / out:  0
Scraping images for id "n02088466" : bloodhound []
 - in:  0 / out:  0
Scraping images for id "n02088632" : bluetick []
 - in:  0 / out:  0
Scraping images for id "n02089078" : black-and-tan_coonhound []
 - in:  0 / out:  0
Scraping images for id "n02089867" : walker_hound []
 - in:  0 / out:  0
Scraping images for id "n02089973" : english_foxhound []
 - in:  0 / out:  0
Scraping images for id "n02090379" : redbone []
 - in:  0 / out:  0
Scraping images for id "n02090622" : borzoi []
 - in:  0 / out:  0
Scraping images for id "n02090721" : irish_wolfhound []
 - in:  0 / out:  0
Scraping images for id "n02091032" : italian_greyhound []
 - in:  0 / out:  0
Scraping images for id "n02091134" : whippet []
 - in:  0 / out:  0
Scraping images for id "n02091244" : ibizan_hound []
 - in:  0 / out:  0
Scraping images for id "n02091467" : norwegian_elkhound []
 - in:  0 / out:  0
Scraping images for id "n02091635" : otterhound []
 - in:  0 / out:  0
Scraping images for id "n02091831" : saluki []
 - in:  0 / out:  0
Scraping images for id "n02092002" : scottish_deerhound []
 - in:  0 / out:  0
Scraping images for id "n02092339" : weimaraner []
 - in:  0 / out:  0
Scraping images for id "n02093256" : staffordshire_bullterrier []
 - in:  0 / out:  0
Scraping images for id "n02093428" : american_staffordshire_terrier []
 - in:  0 / out:  0
Scraping images for id "n02093647" : bedlington_terrier []
 - in:  0 / out:  0
Scraping images for id "n02093754" : border_terrier []
 - in:  0 / out:  0
Scraping images for id "n02093859" : kerry_blue_terrier []
 - in:  0 / out:  0
Scraping images for id "n02093991" : irish_terrier []
 - in:  0 / out:  0
Scraping images for id "n02094114" : norfolk_terrier []
 - in:  0 / out:  0
Scraping images for id "n02094258" : norwich_terrier []
 - in:  0 / out:  0
Scraping images for id "n02094433" : yorkshire_terrier []
 - in:  0 / out:  0
Scraping images for id "n02095314" : wire-haired_fox_terrier []
 - in:  0 / out:  0
Scraping images for id "n02095570" : lakeland_terrier []
 - in:  0 / out:  0
Scraping images for id "n02095889" : sealyham_terrier []
 - in:  0 / out:  0
Scraping images for id "n02096051" : airedale []
 - in:  0 / out:  0
Scraping images for id "n02096177" : cairn []
 - in:  0 / out:  0
Scraping images for id "n02096294" : australian_terrier []
 - in:  0 / out:  0
Scraping images for id "n02096437" : dandie_dinmont []
 - in:  0 / out:  0
Scraping images for id "n02096585" : boston_bull []
 - in:  0 / out:  0
Scraping images for id "n02097047" : miniature_schnauzer []
 - in:  0 / out:  0
Scraping images for id "n02097130" : giant_schnauzer []
 - in:  0 / out:  0
Scraping images for id "n02097209" : standard_schnauzer []
 - in:  0 / out:  0
Scraping images for id "n02097298" : scotch_terrier []
 - in:  0 / out:  0
Scraping images for id "n02097474" : tibetan_terrier []
 - in:  0 / out:  0
Scraping images for id "n02097658" : silky_terrier []
 - in:  0 / out:  0
Scraping images for id "n02098105" : soft-coated_wheaten_terrier []
 - in:  0 / out:  0
Scraping images for id "n02098286" : west_highland_white_terrier []
 - in:  0 / out:  0
Scraping images for id "n02098413" : lhasa []
 - in:  0 / out:  0
Scraping images for id "n02099267" : flat-coated_retriever []
 - in:  0 / out:  0
Scraping images for id "n02099429" : curly-coated_retriever []
 - in:  0 / out:  0
Scraping images for id "n02099601" : golden_retriever []
 - in:  0 / out:  0
Scraping images for id "n02099712" : labrador_retriever []
 - in:  0 / out:  0
Scraping images for id "n02099849" : chesapeake_bay_retriever []
 - in:  0 / out:  0
Scraping images for id "n02100236" : german_short-haired_pointer []
 - in:  0 / out:  0
Scraping images for id "n02100583" : vizsla []
 - in:  0 / out:  0
Scraping images for id "n02100735" : english_setter []
 - in:  0 / out:  0
Scraping images for id "n02100877" : irish_setter []
 - in:  0 / out:  0
Scraping images for id "n02101006" : gordon_setter []
 - in:  0 / out:  0
Scraping images for id "n02101388" : brittany_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02101556" : clumber []
 - in:  0 / out:  0
Scraping images for id "n02102040" : english_springer []
 - in:  0 / out:  0
Scraping images for id "n02102177" : welsh_springer_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02102318" : cocker_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02102480" : sussex_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02102973" : irish_water_spaniel []
 - in:  0 / out:  0
Scraping images for id "n02104029" : kuvasz []
 - in:  0 / out:  0
Scraping images for id "n02104365" : schipperke []
 - in:  0 / out:  0
Scraping images for id "n02105056" : groenendael []
 - in:  0 / out:  0
Scraping images for id "n02105162" : malinois []
 - in:  0 / out:  0
Scraping images for id "n02105251" : briard []
 - in:  0 / out:  0
Scraping images for id "n02105412" : kelpie []
 - in:  0 / out:  0
Scraping images for id "n02105505" : komondor []
 - in:  0 / out:  0
Scraping images for id "n02105641" : old_english_sheepdog []
 - in:  0 / out:  0
Scraping images for id "n02105855" : shetland_sheepdog []
 - in:  0 / out:  0
Scraping images for id "n02106030" : collie []
 - in:  0 / out:  0
Scraping images for id "n02106166" : border_collie []
 - in:  0 / out:  0
Scraping images for id "n02106382" : bouvier_des_flandres []

 - in:  0 / out:  0
Scraping images for id "n02106550" : rottweiler []
 - in:  0 / out:  0
Scraping images for id "n02106662" : german_shepherd []
 - in:  0 / out:  0
Scraping images for id "n02107142" : doberman []
 - in:  0 / out:  0
Scraping images for id "n02107312" : miniature_pinscher []
 - in:  0 / out:  0
Scraping images for id "n02107574" : greater_swiss_mountain_dog []
 - in:  0 / out:  0
Scraping images for id "n02107683" : bernese_mountain_dog []
 - in:  0 / out:  0
Scraping images for id "n02107908" : appenzeller []
 - in:  0 / out:  0
Scraping images for id "n02108000" : entlebucher []
 - in:  0 / out:  0
Scraping images for id "n02108089" : boxer []
 - in:  0 / out:  0
Scraping images for id "n02108422" : bull_mastiff []
 - in:  0 / out:  0
Scraping images for id "n02108551" : tibetan_mastiff []
 - in:  0 / out:  0
Scraping images for id "n02108915" : french_bulldog []
 - in:  0 / out:  0
Scraping images for id "n02109047" : great_dane []
 - in:  0 / out:  0
Scraping images for id "n02109525" : saint_bernard []
 - in:  0 / out:  0
Scraping images for id "n02109961" : eskimo_dog []
 - in:  0 / out:  0
Scraping images for id "n02110063" : malamute []
 - in:  0 / out:  0
Scraping images for id "n02110185" : siberian_husky []
 - in:  0 / out:  0
Scraping images for id "n02110341" : dalmatian []
 - in:  0 / out:  0
Scraping images for id "n02110627" : affenpinscher []
 - in:  0 / out:  0
Scraping images for id "n02110806" : basenji []
 - in:  0 / out:  0
Scraping images for id "n02110958" : pug []
 - in:  0 / out:  0
Scraping images for id "n02111129" : leonberg []
 - in:  0 / out:  0
Scraping images for id "n02111277" : newfoundland []
 - in:  0 / out:  0
Scraping images for id "n02111500" : great_pyrenees []
 - in:  0 / out:  0
Scraping images for id "n02111889" : samoyed []
 - in:  0 / out:  0
Scraping images for id "n02112018" : pomeranian []
 - in:  0 / out:  0
Scraping images for id "n02112137" : chow []
 - in:  0 / out:  0
Scraping images for id "n02112350" : keeshond []
 - in:  0 / out:  0
Scraping images for id "n02112706" : brabancon_griffon []
 - in:  0 / out:  0
Scraping images for id "n02113023" : pembroke []
 - in:  0 / out:  0
Scraping images for id "n02113186" : cardigan []
 - in:  0 / out:  0
Scraping images for id "n02113624" : toy_poodle []
 - in:  0 / out:  0
Scraping images for id "n02113712" : miniature_poodle []
 - in:  0 / out:  0
Scraping images for id "n02113799" : standard_poodle []
 - in:  0 / out:  0
Scraping images for id "n02113978" : mexican_hairless []
 - in:  0 / out:  0
Scraping images for id "n02114367" : timber_wolf []
 - in:  0 / out:  0
Scraping images for id "n02114548" : white_wolf []
 - in:  0 / out:  0
Scraping images for id "n02114712" : red_wolf []
 - in:  0 / out:  0
Scraping images for id "n02114855" : coyote []
 - in:  0 / out:  0
Scraping images for id "n02115641" : dingo []
 - in:  0 / out:  0
Scraping images for id "n02115913" : dhole []
 - in:  0 / out:  0
Scraping images for id "n02116738" : african_hunting_dog []
 - in:  0 / out:  0
Scraping images for id "n02117135" : hyena []
 - in:  0 / out:  0
Scraping images for id "n02119022" : red_fox []
 - in:  0 / out:  0
Scraping images for id "n02119789" : kit_fox []
 - in:  0 / out:  0
Scraping images for id "n02120079" : arctic_fox []
 - in:  0 / out:  0
Scraping images for id "n02120505" : grey_fox []
 - in:  0 / out:  0
Scraping images for id "n02123045" : tabby []
 - in:  0 / out:  0
Scraping images for id "n02123159" : tiger_cat []
 - in:  0 / out:  0
Scraping images for id "n02123394" : persian_cat []
 - in:  0 / out:  0
Scraping images for id "n02123597" : siamese_cat []
 - in:  0 / out:  0
Scraping images for id "n02124075" : egyptian_cat []
 - in:  0 / out:  0
Scraping images for id "n02125311" : cougar []
 - in:  0 / out:  0
Scraping images for id "n02127052" : lynx []
 - in:  0 / out:  0
Scraping images for id "n02128385" : leopard []
 - in:  0 / out:  0
Scraping images for id "n02128757" : snow_leopard []
 - in:  0 / out:  0
Scraping images for id "n02128925" : jaguar []
 - in:  0 / out:  0
Scraping images for id "n02129165" : lion []
 - in:  0 / out:  0
Scraping images for id "n02129604" : tiger []
 - in:  0 / out:  0
Scraping images for id "n02130308" : cheetah []
 - in:  0 / out:  0
Scraping images for id "n02132136" : brown_bear []
 - in:  0 / out:  0
Scraping images for id "n02133161" : american_black_bear []
 - in:  0 / out:  0
Scraping images for id "n02134084" : ice_bear []
 - in:  0 / out:  0
Scraping images for id "n02134418" : sloth_bear []
 - in:  0 / out:  0
Scraping images for id "n02137549" : mongoose []
 - in:  0 / out:  0
Scraping images for id "n02138441" : meerkat []
 - in:  0 / out:  0
Scraping images for id "n02165105" : tiger_beetle []
 - in:  0 / out:  0
Scraping images for id "n02165456" : ladybug []
 - in:  0 / out:  0
Scraping images for id "n02167151" : ground_beetle []
 - in:  0 / out:  0
Scraping images for id "n02168699" : long-horned_beetle []
 - in:  0 / out:  0
Scraping images for id "n02169497" : leaf_beetle []
 - in:  0 / out:  0
Scraping images for id "n02172182" : dung_beetle []
 - in:  0 / out:  0
Scraping images for id "n02174001" : rhinoceros_beetle []
 - in:  0 / out:  0
Scraping images for id "n02177972" : weevil []
 - in:  0 / out:  0
Scraping images for id "n02190166" : fly []
 - in:  0 / out:  0
Scraping images for id "n02206856" : bee []
 - in:  0 / out:  0
Scraping images for id "n02219486" : ant []
 - in:  0 / out:  0
Scraping images for id "n02226429" : grasshopper []
 - in:  0 / out:  0
Scraping images for id "n02229544" : cricket []
 - in:  0 / out:  0
Scraping images for id "n02231487" : walking_stick

[]
 - in:  0 / out:  0
Scraping images for id "n02233338" : cockroach []
 - in:  0 / out:  0
Scraping images for id "n02236044" : mantis []
 - in:  0 / out:  0
Scraping images for id "n02256656" : cicada []
 - in:  0 / out:  0
Scraping images for id "n02259212" : leafhopper []
 - in:  0 / out:  0
Scraping images for id "n02264363" : lacewing []
 - in:  0 / out:  0
Scraping images for id "n02268443" : dragonfly []
 - in:  0 / out:  0
Scraping images for id "n02268853" : damselfly []
 - in:  0 / out:  0
Scraping images for id "n02276258" : admiral []
 - in:  0 / out:  0
Scraping images for id "n02277742" : ringlet []
 - in:  0 / out:  0
Scraping images for id "n02279972" : monarch []
 - in:  0 / out:  0
Scraping images for id "n02280649" : cabbage_butterfly []
 - in:  0 / out:  0
Scraping images for id "n02281406" : sulphur_butterfly []
 - in:  0 / out:  0
Scraping images for id "n02281787" : lycaenid []
 - in:  0 / out:  0
Scraping images for id "n02317335" : starfish []
 - in:  0 / out:  0
Scraping images for id "n02319095" : sea_urchin []
 - in:  0 / out:  0
Scraping images for id "n02321529" : sea_cucumber []
 - in:  0 / out:  0
Scraping images for id "n02325366" : wood_rabbit []
 - in:  0 / out:  0
Scraping images for id "n02326432" : hare []
 - in:  0 / out:  0
Scraping images for id "n02328150" : angora []
 - in:  0 / out:  0
Scraping images for id "n02342885" : hamster []
 - in:  0 / out:  0
Scraping images for id "n02346627" : porcupine []
 - in:  0 / out:  0
Scraping images for id "n02356798" : fox_squirrel []
 - in:  0 / out:  0
Scraping images for id "n02361337" : marmot []
 - in:  0 / out:  0
Scraping images for id "n02363005" : beaver []
 - in:  0 / out:  0
Scraping images for id "n02364673" : guinea_pig []
 - in:  0 / out:  0
Scraping images for id "n02389026" : sorrel []
 - in:  0 / out:  0
Scraping images for id "n02391049" : zebra []
 - in:  0 / out:  0
Scraping images for id "n02395406" : hog []
 - in:  0 / out:  0
Scraping images for id "n02396427" : wild_boar []
 - in:  0 / out:  0
Scraping images for id "n02397096" : warthog []
 - in:  0 / out:  0
Scraping images for id "n02398521" : hippopotamus []
 - in:  0 / out:  0
Scraping images for id "n02403003" : ox []
 - in:  0 / out:  0
Scraping images for id "n02408429" : water_buffalo []
 - in:  0 / out:  0
Scraping images for id "n02410509" : bison []
 - in:  0 / out:  0
Scraping images for id "n02412080" : ram []
 - in:  0 / out:  0
Scraping images for id "n02415577" : bighorn []
 - in:  0 / out:  0
Scraping images for id "n02417914" : ibex []
 - in:  0 / out:  0
Scraping images for id "n02422106" : hartebeest []
 - in:  0 / out:  0
Scraping images for id "n02422699" : impala []
 - in:  0 / out:  0
Scraping images for id "n02423022" : gazelle []
 - in:  0 / out:  0
Scraping images for id "n02437312" : arabian_camel []
 - in:  0 / out:  0
Scraping images for id "n02437616" : llama []
 - in:  0 / out:  0
Scraping images for id "n02441942" : weasel []
 - in:  0 / out:  0
Scraping images for id "n02442845" : mink []
 - in:  0 / out:  0
Scraping images for id "n02443114" : polecat []
 - in:  0 / out:  0
Scraping images for id "n02443484" : black-footed_ferret []
 - in:  0 / out:  0
Scraping images for id "n02444819" : otter []
 - in:  0 / out:  0
Scraping images for id "n02445715" : skunk []
 - in:  0 / out:  0
Scraping images for id "n02447366" : badger []
 - in:  0 / out:  0
Scraping images for id "n02454379" : armadillo []
 - in:  0 / out:  0
Scraping images for id "n02457408" : three-toed_sloth []
 - in:  0 / out:  0
Scraping images for id "n02480495" : orangutan []
 - in:  0 / out:  0
Scraping images for id "n02480855" : gorilla []
 - in:  0 / out:  0
Scraping images for id "n02481823" : chimpanzee []
 - in:  0 / out:  0
Scraping images for id "n02483362" : gibbon []
 - in:  0 / out:  0
Scraping images for id "n02483708" : siamang []
 - in:  0 / out:  0
Scraping images for id "n02484975" : guenon []
 - in:  0 / out:  0
Scraping images for id "n02486261" : patas []
 - in:  0 / out:  0
Scraping images for id "n02486410" : baboon []
 - in:  0 / out:  0
Scraping images for id "n02487347" : macaque []
 - in:  0 / out:  0
Scraping images for id "n02488291" : langur []
 - in:  0 / out:  0
Scraping images for id "n02488702" : colobus []
 - in:  0 / out:  0
Scraping images for id "n02489166" : proboscis_monkey []
 - in:  0 / out:  0
Scraping images for id "n02490219" : marmoset []
 - in:  0 / out:  0
Scraping images for id "n02492035" : capuchin []
 - in:  0 / out:  0
Scraping images for id "n02492660" : howler_monkey []
 - in:  0 / out:  0
Scraping images for id "n02493509" : titi []
 - in:  0 / out:  0
Scraping images for id "n02493793" : spider_monkey []
 - in:  0 / out:  0
Scraping images for id "n02494079" : squirrel_monkey []
 - in:  0 / out:  0
Scraping images for id "n02497673" : madagascar_cat []
 - in:  0 / out:  0
Scraping images for id "n02500267" : indri []
 - in:  0 / out:  0
Scraping images for id "n02504013" : indian_elephant []
 - in:  0 / out:  0
Scraping images for id "n02504458" : african_elephant []
 - in:  0 / out:  0
Scraping images for id "n02509815" : lesser_panda []
 - in:  0 / out:  0
Scraping images for id "n02510455" : giant_panda []
 - in:  0 / out:  0
Scraping images for id "n02514041" : barracouta []
 - in:  0 / out:  0
Scraping images for id "n02526121" : eel []
 - in:  0 / out:  0
Scraping images for id "n02536864" : coho []
 - in:  0 / out:  0
Scraping images for id "n02606052" : rock_beauty []
 - in:  0 / out:  0
Scraping images for id "n02607072" : anemone_fish []
 - in:  0 / out:  0
Scraping images for id "n02640242" : sturgeon []
 - in:  0 / out:  0
Scraping images for id "n02641379" : gar []
 - in:  0 / out:  0
Scraping images for id "n02643566" : lionfish []
 - in:  0 / out:  0
Scraping images for id "n02655020" : puffer []
 - in:  0 / out:  0
Scraping images for id "n02666196" : abacus []
 - in:  0 / out:  0
Scraping images for id "n02667093" : abaya []
 - in:  0 / out:  0
Scraping images for id "n02669723" : academic_gown []

 - in:  0 / out:  0
Scraping images for id "n02672831" : accordion []
 - in:  0 / out:  0
Scraping images for id "n02676566" : acoustic_guitar []
 - in:  0 / out:  0
Scraping images for id "n02687172" : aircraft_carrier []
 - in:  0 / out:  0
Scraping images for id "n02690373" : airliner []
 - in:  0 / out:  0
Scraping images for id "n02692877" : airship []
 - in:  0 / out:  0
Scraping images for id "n02699494" : altar []
 - in:  0 / out:  0
Scraping images for id "n02701002" : ambulance []
 - in:  0 / out:  0
Scraping images for id "n02704792" : amphibian []
 - in:  0 / out:  0
Scraping images for id "n02708093" : analog_clock []
 - in:  0 / out:  0
Scraping images for id "n02727426" : apiary []
 - in:  0 / out:  0
Scraping images for id "n02730930" : apron []
 - in:  0 / out:  0
Scraping images for id "n02747177" : ashcan []
 - in:  0 / out:  0
Scraping images for id "n02749479" : assault_rifle []
 - in:  0 / out:  0
Scraping images for id "n02769748" : backpack []
 - in:  0 / out:  0
Scraping images for id "n02776631" : bakery []
 - in:  0 / out:  0
Scraping images for id "n02777292" : balance_beam []
 - in:  0 / out:  0
Scraping images for id "n02782093" : balloon []
 - in:  0 / out:  0
Scraping images for id "n02783161" : ballpoint []
 - in:  0 / out:  0
Scraping images for id "n02786058" : band_aid []
 - in:  0 / out:  0
Scraping images for id "n02787622" : banjo []
 - in:  0 / out:  0
Scraping images for id "n02788148" : bannister []
 - in:  0 / out:  0
Scraping images for id "n02790996" : barbell []
 - in:  0 / out:  0
Scraping images for id "n02791124" : barber_chair []
 - in:  0 / out:  0
Scraping images for id "n02791270" : barbershop []
 - in:  0 / out:  0
Scraping images for id "n02793495" : barn []
 - in:  0 / out:  0
Scraping images for id "n02794156" : barometer []
 - in:  0 / out:  0
Scraping images for id "n02795169" : barrel []
 - in:  0 / out:  0
Scraping images for id "n02797295" : barrow []
 - in:  0 / out:  0
Scraping images for id "n02799071" : baseball []
 - in:  0 / out:  0
Scraping images for id "n02802426" : basketball []
 - in:  0 / out:  0
Scraping images for id "n02804414" : bassinet []
 - in:  0 / out:  0
Scraping images for id "n02804610" : bassoon []
 - in:  0 / out:  0
Scraping images for id "n02807133" : bathing_cap []
 - in:  0 / out:  0
Scraping images for id "n02808304" : bath_towel []
 - in:  0 / out:  0
Scraping images for id "n02808440" : bathtub []
 - in:  0 / out:  0
Scraping images for id "n02814533" : beach_wagon []
 - in:  0 / out:  0
Scraping images for id "n02814860" : beacon []
 - in:  0 / out:  0
Scraping images for id "n02815834" : beaker []
 - in:  0 / out:  0
Scraping images for id "n02817516" : bearskin []
 - in:  0 / out:  0
Scraping images for id "n02823428" : beer_bottle []
 - in:  0 / out:  0
Scraping images for id "n02823750" : beer_glass []
 - in:  0 / out:  0
Scraping images for id "n02825657" : bell_cote []
 - in:  0 / out:  0
Scraping images for id "n02834397" : bib []
 - in:  0 / out:  0
Scraping images for id "n02835271" : bicycle-built-for-two []
 - in:  0 / out:  0
Scraping images for id "n02837789" : bikini []
 - in:  0 / out:  0
Scraping images for id "n02840245" : binder []
 - in:  0 / out:  0
Scraping images for id "n02841315" : binoculars []
 - in:  0 / out:  0
Scraping images for id "n02843684" : birdhouse []
 - in:  0 / out:  0
Scraping images for id "n02859443" : boathouse []
 - in:  0 / out:  0
Scraping images for id "n02860847" : bobsled []
 - in:  0 / out:  0
Scraping images for id "n02865351" : bolo_tie []
 - in:  0 / out:  0
Scraping images for id "n02869837" : bonnet []
 - in:  0 / out:  0
Scraping images for id "n02870880" : bookcase []
 - in:  0 / out:  0
Scraping images for id "n02871525" : bookshop []
 - in:  0 / out:  0
Scraping images for id "n02877765" : bottlecap []
 - in:  0 / out:  0
Scraping images for id "n02879718" : bow []
 - in:  0 / out:  0
Scraping images for id "n02883205" : bow_tie []
 - in:  0 / out:  0
Scraping images for id "n02892201" : brass []
 - in:  0 / out:  0
Scraping images for id "n02892767" : brassiere []
 - in:  0 / out:  0
Scraping images for id "n02894605" : breakwater []
 - in:  0 / out:  0
Scraping images for id "n02895154" : breastplate []
 - in:  0 / out:  0
Scraping images for id "n02906734" : broom []
 - in:  0 / out:  0
Scraping images for id "n02909870" : bucket []
 - in:  0 / out:  0
Scraping images for id "n02910353" : buckle []
 - in:  0 / out:  0
Scraping images for id "n02916936" : bulletproof_vest []
 - in:  0 / out:  0
Scraping images for id "n02917067" : bullet_train []
 - in:  0 / out:  0
Scraping images for id "n02927161" : butcher_shop []
 - in:  0 / out:  0
Scraping images for id "n02930766" : cab []
 - in:  0 / out:  0
Scraping images for id "n02939185" : caldron []
 - in:  0 / out:  0
Scraping images for id "n02948072" : candle []
 - in:  0 / out:  0
Scraping images for id "n02950826" : cannon []
 - in:  0 / out:  0
Scraping images for id "n02951358" : canoe []
 - in:  0 / out:  0
Scraping images for id "n02951585" : can_opener []
 - in:  0 / out:  0
Scraping images for id "n02963159" : cardigan []
 - in:  0 / out:  0
Scraping images for id "n02965783" : car_mirror []
 - in:  0 / out:  0
Scraping images for id "n02966193" : carousel []
 - in:  0 / out:  0
Scraping images for id "n02966687" : carpenter's_kit []
 - in:  0 / out:  0
Scraping images for id "n02971356" : carton []
 - in:  0 / out:  0
Scraping images for id "n02974003" : car_wheel []
 - in:  0 / out:  0
Scraping images for id "n02977058" : cash_machine []
 - in:  0 / out:  0
Scraping images for id "n02978881" : cassette []

 - in:  0 / out:  0
Scraping images for id "n02979186" : cassette_player []
 - in:  0 / out:  0
Scraping images for id "n02980441" : castle []
 - in:  0 / out:  0
Scraping images for id "n02981792" : catamaran []
 - in:  0 / out:  0
Scraping images for id "n02988304" : cd_player []
 - in:  0 / out:  0
Scraping images for id "n02992211" : cello []
 - in:  0 / out:  0
Scraping images for id "n02992529" : cellular_telephone []
 - in:  0 / out:  0
Scraping images for id "n02999410" : chain []
 - in:  0 / out:  0
Scraping images for id "n03000134" : chainlink_fence []
 - in:  0 / out:  0
Scraping images for id "n03000247" : chain_mail []
 - in:  0 / out:  0
Scraping images for id "n03000684" : chain_saw []
 - in:  0 / out:  0
Scraping images for id "n03014705" : chest []
 - in:  0 / out:  0
Scraping images for id "n03016953" : chiffonier []
 - in:  0 / out:  0
Scraping images for id "n03017168" : chime []
 - in:  0 / out:  0
Scraping images for id "n03018349" : china_cabinet []
 - in:  0 / out:  0
Scraping images for id "n03026506" : christmas_stocking []
 - in:  0 / out:  0
Scraping images for id "n03028079" : church []
 - in:  0 / out:  0
Scraping images for id "n03032252" : cinema []
 - in:  0 / out:  0
Scraping images for id "n03041632" : cleaver []
 - in:  0 / out:  0
Scraping images for id "n03042490" : cliff_dwelling []
 - in:  0 / out:  0
Scraping images for id "n03045698" : cloak []
 - in:  0 / out:  0
Scraping images for id "n03047690" : clog []
 - in:  0 / out:  0
Scraping images for id "n03062245" : cocktail_shaker []
 - in:  0 / out:  0
Scraping images for id "n03063599" : coffee_mug []
 - in:  0 / out:  0
Scraping images for id "n03063689" : coffeepot []
 - in:  0 / out:  0
Scraping images for id "n03065424" : coil []
 - in:  0 / out:  0
Scraping images for id "n03075370" : combination_lock []
 - in:  0 / out:  0
Scraping images for id "n03085013" : computer_keyboard []
 - in:  0 / out:  0
Scraping images for id "n03089624" : confectionery []
 - in:  0 / out:  0
Scraping images for id "n03095699" : container_ship []
 - in:  0 / out:  0
Scraping images for id "n03100240" : convertible []
 - in:  0 / out:  0
Scraping images for id "n03109150" : corkscrew []
 - in:  0 / out:  0
Scraping images for id "n03110669" : cornet []
 - in:  0 / out:  0
Scraping images for id "n03124043" : cowboy_boot []
 - in:  0 / out:  0
Scraping images for id "n03124170" : cowboy_hat []
 - in:  0 / out:  0
Scraping images for id "n03125729" : cradle []
 - in:  0 / out:  0
Scraping images for id "n03126707" : crane []
 - in:  0 / out:  0
Scraping images for id "n03127747" : crash_helmet []
 - in:  0 / out:  0
Scraping images for id "n03127925" : crate []
 - in:  0 / out:  0
Scraping images for id "n03131574" : crib []
 - in:  0 / out:  0
Scraping images for id "n03133878" : crock_pot []
 - in:  0 / out:  0
Scraping images for id "n03134739" : croquet_ball []
 - in:  0 / out:  0
Scraping images for id "n03141823" : crutch []
 - in:  0 / out:  0
Scraping images for id "n03146219" : cuirass []
 - in:  0 / out:  0
Scraping images for id "n03160309" : dam []
 - in:  0 / out:  0
Scraping images for id "n03179701" : desk []
 - in:  0 / out:  0
Scraping images for id "n03180011" : desktop_computer []
 - in:  0 / out:  0
Scraping images for id "n03187595" : dial_telephone []
 - in:  0 / out:  0
Scraping images for id "n03188531" : diaper []
 - in:  0 / out:  0
Scraping images for id "n03196217" : digital_clock []
 - in:  0 / out:  0
Scraping images for id "n03197337" : digital_watch []
 - in:  0 / out:  0
Scraping images for id "n03201208" : dining_table []
 - in:  0 / out:  0
Scraping images for id "n03207743" : dishrag []
 - in:  0 / out:  0
Scraping images for id "n03207941" : dishwasher []
 - in:  0 / out:  0
Scraping images for id "n03208938" : disk_brake []
 - in:  0 / out:  0
Scraping images for id "n03216828" : dock []
 - in:  0 / out:  0
Scraping images for id "n03218198" : dogsled []
 - in:  0 / out:  0
Scraping images for id "n03220513" : dome []
 - in:  0 / out:  0
Scraping images for id "n03223299" : doormat []
 - in:  0 / out:  0
Scraping images for id "n03240683" : drilling_platform []
 - in:  0 / out:  0
Scraping images for id "n03249569" : drum []
 - in:  0 / out:  0
Scraping images for id "n03250847" : drumstick []
 - in:  0 / out:  0
Scraping images for id "n03255030" : dumbbell []
 - in:  0 / out:  0
Scraping images for id "n03259280" : dutch_oven []
 - in:  0 / out:  0
Scraping images for id "n03271574" : electric_fan []
 - in:  0 / out:  0
Scraping images for id "n03272010" : electric_guitar []
 - in:  0 / out:  0
Scraping images for id "n03272562" : electric_locomotive []
 - in:  0 / out:  0
Scraping images for id "n03290653" : entertainment_center []
 - in:  0 / out:  0
Scraping images for id "n03291819" : envelope []
 - in:  0 / out:  0
Scraping images for id "n03297495" : espresso_maker []
 - in:  0 / out:  0
Scraping images for id "n03314780" : face_powder []
 - in:  0 / out:  0
Scraping images for id "n03325584" : feather_boa []
 - in:  0 / out:  0
Scraping images for id "n03337140" : file []
 - in:  0 / out:  0
Scraping images for id "n03344393" : fireboat []
 - in:  0 / out:  0
Scraping images for id "n03345487" : fire_engine []
 - in:  0 / out:  0
Scraping images for id "n03347037" : fire_screen []
 - in:  0 / out:  0
Scraping images for id "n03355925" : flagpole []
 - in:  0 / out:  0
Scraping images for id "n03372029" : flute []
 - in:  0 / out:  0
Scraping images for id "n03376595" : folding_chair []
 - in:  0 / out:  0
Scraping images for id "n03379051" : football_helmet []
 - in:  0 / out:  0
Scraping images for id "n03384352" : forklift []
 - in:  0 / out:  0
Scraping images for id "n03388043" : fountain []
 - in:  0 / out:  0
Scraping images for id "n03388183" : fountain_pen []

 - in:  0 / out:  0
Scraping images for id "n03388549" : four-poster []
 - in:  0 / out:  0
Scraping images for id "n03393912" : freight_car []
 - in:  0 / out:  0
Scraping images for id "n03394916" : french_horn []
 - in:  0 / out:  0
Scraping images for id "n03400231" : frying_pan []
 - in:  0 / out:  0
Scraping images for id "n03404251" : fur_coat []
 - in:  0 / out:  0
Scraping images for id "n03417042" : garbage_truck []
 - in:  0 / out:  0
Scraping images for id "n03424325" : gasmask []
 - in:  0 / out:  0
Scraping images for id "n03425413" : gas_pump []
 - in:  0 / out:  0
Scraping images for id "n03443371" : goblet []
 - in:  0 / out:  0
Scraping images for id "n03444034" : go-kart []
 - in:  0 / out:  0
Scraping images for id "n03445777" : golf_ball []
 - in:  0 / out:  0
Scraping images for id "n03445924" : golfcart []
 - in:  0 / out:  0
Scraping images for id "n03447447" : gondola []
 - in:  0 / out:  0
Scraping images for id "n03447721" : gong []
 - in:  0 / out:  0
Scraping images for id "n03450230" : gown []
 - in:  0 / out:  0
Scraping images for id "n03452741" : grand_piano []
 - in:  0 / out:  0
Scraping images for id "n03457902" : greenhouse []
 - in:  0 / out:  0
Scraping images for id "n03459775" : grille []
 - in:  0 / out:  0
Scraping images for id "n03461385" : grocery_store []
 - in:  0 / out:  0
Scraping images for id "n03467068" : guillotine []
 - in:  0 / out:  0
Scraping images for id "n03476684" : hair_slide []
 - in:  0 / out:  0
Scraping images for id "n03476991" : hair_spray []
 - in:  0 / out:  0
Scraping images for id "n03478589" : half_track []
 - in:  0 / out:  0
Scraping images for id "n03481172" : hammer []
 - in:  0 / out:  0
Scraping images for id "n03482405" : hamper []
 - in:  0 / out:  0
Scraping images for id "n03483316" : hand_blower []
 - in:  0 / out:  0
Scraping images for id "n03485407" : hand-held_computer []
 - in:  0 / out:  0
Scraping images for id "n03485794" : handkerchief []
 - in:  0 / out:  0
Scraping images for id "n03492542" : hard_disc []
 - in:  0 / out:  0
Scraping images for id "n03494278" : harmonica []
 - in:  0 / out:  0
Scraping images for id "n03495258" : harp []
 - in:  0 / out:  0
Scraping images for id "n03496892" : harvester []
 - in:  0 / out:  0
Scraping images for id "n03498962" : hatchet []
 - in:  0 / out:  0
Scraping images for id "n03527444" : holster []
 - in:  0 / out:  0
Scraping images for id "n03529860" : home_theater []
 - in:  0 / out:  0
Scraping images for id "n03530642" : honeycomb []
 - in:  0 / out:  0
Scraping images for id "n03532672" : hook []
 - in:  0 / out:  0
Scraping images for id "n03534580" : hoopskirt []
 - in:  0 / out:  0
Scraping images for id "n03535780" : horizontal_bar []
 - in:  0 / out:  0
Scraping images for id "n03538406" : horse_cart []
 - in:  0 / out:  0
Scraping images for id "n03544143" : hourglass []
 - in:  0 / out:  0
Scraping images for id "n03584254" : ipod []
 - in:  0 / out:  0
Scraping images for id "n03584829" : iron []
 - in:  0 / out:  0
Scraping images for id "n03590841" : jack-o'-lantern []
 - in:  0 / out:  0
Scraping images for id "n03594734" : jean []
 - in:  0 / out:  0
Scraping images for id "n03594945" : jeep []
 - in:  0 / out:  0
Scraping images for id "n03595614" : jersey []
 - in:  0 / out:  0
Scraping images for id "n03598930" : jigsaw_puzzle []
 - in:  0 / out:  0
Scraping images for id "n03599486" : jinrikisha []
 - in:  0 / out:  0
Scraping images for id "n03602883" : joystick []
 - in:  0 / out:  0
Scraping images for id "n03617480" : kimono []
 - in:  0 / out:  0
Scraping images for id "n03623198" : knee_pad []
 - in:  0 / out:  0
Scraping images for id "n03627232" : knot []
 - in:  0 / out:  0
Scraping images for id "n03630383" : lab_coat []
 - in:  0 / out:  0
Scraping images for id "n03633091" : ladle []
 - in:  0 / out:  0
Scraping images for id "n03637318" : lampshade []
 - in:  0 / out:  0
Scraping images for id "n03642806" : laptop []
 - in:  0 / out:  0
Scraping images for id "n03649909" : lawn_mower []
 - in:  0 / out:  0
Scraping images for id "n03657121" : lens_cap []
 - in:  0 / out:  0
Scraping images for id "n03658185" : letter_opener []
 - in:  0 / out:  0
Scraping images for id "n03661043" : library []
 - in:  0 / out:  0
Scraping images for id "n03662601" : lifeboat []
 - in:  0 / out:  0
Scraping images for id "n03666591" : lighter []
 - in:  0 / out:  0
Scraping images for id "n03670208" : limousine []
 - in:  0 / out:  0
Scraping images for id "n03673027" : liner []
 - in:  0 / out:  0
Scraping images for id "n03676483" : lipstick []
 - in:  0 / out:  0
Scraping images for id "n03680355" : loafer []
 - in:  0 / out:  0
Scraping images for id "n03690938" : lotion []
 - in:  0 / out:  0
Scraping images for id "n03691459" : loudspeaker []
 - in:  0 / out:  0
Scraping images for id "n03692522" : loupe []
 - in:  0 / out:  0
Scraping images for id "n03697007" : lumbermill []
 - in:  0 / out:  0
Scraping images for id "n03706229" : magnetic_compass []
 - in:  0 / out:  0
Scraping images for id "n03709823" : mailbag []
 - in:  0 / out:  0
Scraping images for id "n03710193" : mailbox []
 - in:  0 / out:  0
Scraping images for id "n03710637" : maillot []
 - in:  0 / out:  0
Scraping images for id "n03710721" : maillot []
 - in:  0 / out:  0
Scraping images for id "n03717622" : manhole_cover []
 - in:  0 / out:  0
Scraping images for id "n03720891" : maraca []
 - in:  0 / out:  0
Scraping images for id "n03721384" : marimba []
 - in:  0 / out:  0
Scraping images for id "n03724870" : mask []
 - in:  0 / out:  0
Scraping images for id "n03729826" : matchstick []
 - in:  0 / out:  0
Scraping images for id "n03733131" : maypole []
 - in:  0 / out:  0
Scraping images for id "n03733281" : maze

[]
 - in:  0 / out:  0
Scraping images for id "n03733805" : measuring_cup []
 - in:  0 / out:  0
Scraping images for id "n03742115" : medicine_chest []
 - in:  0 / out:  0
Scraping images for id "n03743016" : megalith []
 - in:  0 / out:  0
Scraping images for id "n03759954" : microphone []
 - in:  0 / out:  0
Scraping images for id "n03761084" : microwave []
 - in:  0 / out:  0
Scraping images for id "n03763968" : military_uniform []
 - in:  0 / out:  0
Scraping images for id "n03764736" : milk_can []
 - in:  0 / out:  0
Scraping images for id "n03769881" : minibus []
 - in:  0 / out:  0
Scraping images for id "n03770439" : miniskirt []
 - in:  0 / out:  0
Scraping images for id "n03770679" : minivan []
 - in:  0 / out:  0
Scraping images for id "n03773504" : missile []
 - in:  0 / out:  0
Scraping images for id "n03775071" : mitten []
 - in:  0 / out:  0
Scraping images for id "n03775546" : mixing_bowl []
 - in:  0 / out:  0
Scraping images for id "n03776460" : mobile_home []
 - in:  0 / out:  0
Scraping images for id "n03777568" : model_t []
 - in:  0 / out:  0
Scraping images for id "n03777754" : modem []
 - in:  0 / out:  0
Scraping images for id "n03781244" : monastery []
 - in:  0 / out:  0
Scraping images for id "n03782006" : monitor []
 - in:  0 / out:  0
Scraping images for id "n03785016" : moped []
 - in:  0 / out:  0
Scraping images for id "n03786901" : mortar []
 - in:  0 / out:  0
Scraping images for id "n03787032" : mortarboard []
 - in:  0 / out:  0
Scraping images for id "n03788195" : mosque []
 - in:  0 / out:  0
Scraping images for id "n03788365" : mosquito_net []
 - in:  0 / out:  0
Scraping images for id "n03791053" : motor_scooter []
 - in:  0 / out:  0
Scraping images for id "n03792782" : mountain_bike []
 - in:  0 / out:  0
Scraping images for id "n03792972" : mountain_tent []
 - in:  0 / out:  0
Scraping images for id "n03793489" : mouse []
 - in:  0 / out:  0
Scraping images for id "n03794056" : mousetrap []
 - in:  0 / out:  0
Scraping images for id "n03796401" : moving_van []
 - in:  0 / out:  0
Scraping images for id "n03803284" : muzzle []
 - in:  0 / out:  0
Scraping images for id "n03804744" : nail []
 - in:  0 / out:  0
Scraping images for id "n03814639" : neck_brace []
 - in:  0 / out:  0
Scraping images for id "n03814906" : necklace []
 - in:  0 / out:  0
Scraping images for id "n03825788" : nipple []
 - in:  0 / out:  0
Scraping images for id "n03832673" : notebook []
 - in:  0 / out:  0
Scraping images for id "n03837869" : obelisk []
 - in:  0 / out:  0
Scraping images for id "n03838899" : oboe []
 - in:  0 / out:  0
Scraping images for id "n03840681" : ocarina []
 - in:  0 / out:  0
Scraping images for id "n03841143" : odometer []
 - in:  0 / out:  0
Scraping images for id "n03843555" : oil_filter []
 - in:  0 / out:  0
Scraping images for id "n03854065" : organ []
 - in:  0 / out:  0
Scraping images for id "n03857828" : oscilloscope []
 - in:  0 / out:  0
Scraping images for id "n03866082" : overskirt []
 - in:  0 / out:  0
Scraping images for id "n03868242" : oxcart []
 - in:  0 / out:  0
Scraping images for id "n03868863" : oxygen_mask []
 - in:  0 / out:  0
Scraping images for id "n03871628" : packet []
 - in:  0 / out:  0
Scraping images for id "n03873416" : paddle []
 - in:  0 / out:  0
Scraping images for id "n03874293" : paddlewheel []
 - in:  0 / out:  0
Scraping images for id "n03874599" : padlock []
 - in:  0 / out:  0
Scraping images for id "n03876231" : paintbrush []
 - in:  0 / out:  0
Scraping images for id "n03877472" : pajama []
 - in:  0 / out:  0
Scraping images for id "n03877845" : palace []
 - in:  0 / out:  0
Scraping images for id "n03884397" : panpipe []
 - in:  0 / out:  0
Scraping images for id "n03887697" : paper_towel []
 - in:  0 / out:  0
Scraping images for id "n03888257" : parachute []
 - in:  0 / out:  0
Scraping images for id "n03888605" : parallel_bars []
 - in:  0 / out:  0
Scraping images for id "n03891251" : park_bench []
 - in:  0 / out:  0
Scraping images for id "n03891332" : parking_meter []
 - in:  0 / out:  0
Scraping images for id "n03895866" : passenger_car []
 - in:  0 / out:  0
Scraping images for id "n03899768" : patio []
 - in:  0 / out:  0
Scraping images for id "n03902125" : pay-phone []
 - in:  0 / out:  0
Scraping images for id "n03903868" : pedestal []
 - in:  0 / out:  0
Scraping images for id "n03908618" : pencil_box []
 - in:  0 / out:  0
Scraping images for id "n03908714" : pencil_sharpener []
 - in:  0 / out:  0
Scraping images for id "n03916031" : perfume []
 - in:  0 / out:  0
Scraping images for id "n03920288" : petri_dish []
 - in:  0 / out:  0
Scraping images for id "n03924679" : photocopier []
 - in:  0 / out:  0
Scraping images for id "n03929660" : pick []
 - in:  0 / out:  0
Scraping images for id "n03929855" : pickelhaube []
 - in:  0 / out:  0
Scraping images for id "n03930313" : picket_fence []
 - in:  0 / out:  0
Scraping images for id "n03930630" : pickup []
 - in:  0 / out:  0
Scraping images for id "n03933933" : pier []
 - in:  0 / out:  0
Scraping images for id "n03935335" : piggy_bank []
 - in:  0 / out:  0
Scraping images for id "n03937543" : pill_bottle []
 - in:  0 / out:  0
Scraping images for id "n03938244" : pillow []
 - in:  0 / out:  0
Scraping images for id "n03942813" : ping-pong_ball []
 - in:  0 / out:  0
Scraping images for id "n03944341" : pinwheel []
 - in:  0 / out:  0
Scraping images for id "n03947888" : pirate []
 - in:  0 / out:  0
Scraping images for id "n03950228" : pitcher []
 - in:  0 / out:  0
Scraping images for id "n03954731" : plane []
 - in:  0 / out:  0
Scraping images for id "n03956157" : planetarium []
 - in:  0 / out:  0
Scraping images for id "n03958227" : plastic_bag []
 - in:  0 / out:  0
Scraping images for id "n03961711" : plate_rack []
 - in:  0 / out:  0
Scraping images for id "n03967562" : plow []
 - in:  0 / out:  0
Scraping images for id "n03970156" : plunger

[]
 - in:  0 / out:  0
Scraping images for id "n03976467" : polaroid_camera []
 - in:  0 / out:  0
Scraping images for id "n03976657" : pole []
 - in:  0 / out:  0
Scraping images for id "n03977966" : police_van []
 - in:  0 / out:  0
Scraping images for id "n03980874" : poncho []
 - in:  0 / out:  0
Scraping images for id "n03982430" : pool_table []
 - in:  0 / out:  0
Scraping images for id "n03983396" : pop_bottle []
 - in:  0 / out:  0
Scraping images for id "n03991062" : pot []
 - in:  0 / out:  0
Scraping images for id "n03992509" : potter's_wheel []
 - in:  0 / out:  0
Scraping images for id "n03995372" : power_drill []
 - in:  0 / out:  0
Scraping images for id "n03998194" : prayer_rug []
 - in:  0 / out:  0
Scraping images for id "n04004767" : printer []
 - in:  0 / out:  0
Scraping images for id "n04005630" : prison []
 - in:  0 / out:  0
Scraping images for id "n04008634" : projectile []
 - in:  0 / out:  0
Scraping images for id "n04009552" : projector []
 - in:  0 / out:  0
Scraping images for id "n04019541" : puck []
 - in:  0 / out:  0
Scraping images for id "n04023962" : punching_bag []
 - in:  0 / out:  0
Scraping images for id "n04026417" : purse []
 - in:  0 / out:  0
Scraping images for id "n04033901" : quill []
 - in:  0 / out:  0
Scraping images for id "n04033995" : quilt []
 - in:  0 / out:  0
Scraping images for id "n04037443" : racer []
 - in:  0 / out:  0
Scraping images for id "n04039381" : racket []
 - in:  0 / out:  0
Scraping images for id "n04040759" : radiator []
 - in:  0 / out:  0
Scraping images for id "n04041544" : radio []
 - in:  0 / out:  0
Scraping images for id "n04044716" : radio_telescope []
 - in:  0 / out:  0
Scraping images for id "n04049303" : rain_barrel []
 - in:  0 / out:  0
Scraping images for id "n04065272" : recreational_vehicle []
 - in:  0 / out:  0
Scraping images for id "n04067472" : reel []
 - in:  0 / out:  0
Scraping images for id "n04069434" : reflex_camera []
 - in:  0 / out:  0
Scraping images for id "n04070727" : refrigerator []
 - in:  0 / out:  0
Scraping images for id "n04074963" : remote_control []
 - in:  0 / out:  0
Scraping images for id "n04081281" : restaurant []
 - in:  0 / out:  0
Scraping images for id "n04086273" : revolver []
 - in:  0 / out:  0
Scraping images for id "n04090263" : rifle []
 - in:  0 / out:  0
Scraping images for id "n04099969" : rocking_chair []
 - in:  0 / out:  0
Scraping images for id "n04111531" : rotisserie []
 - in:  0 / out:  0
Scraping images for id "n04116512" : rubber_eraser []
 - in:  0 / out:  0
Scraping images for id "n04118538" : rugby_ball []
 - in:  0 / out:  0
Scraping images for id "n04118776" : rule []
 - in:  0 / out:  0
Scraping images for id "n04120489" : running_shoe []
 - in:  0 / out:  0
Scraping images for id "n04125021" : safe []
 - in:  0 / out:  0
Scraping images for id "n04127249" : safety_pin []
 - in:  0 / out:  0
Scraping images for id "n04131690" : saltshaker []
 - in:  0 / out:  0
Scraping images for id "n04133789" : sandal []
 - in:  0 / out:  0
Scraping images for id "n04136333" : sarong []
 - in:  0 / out:  0
Scraping images for id "n04141076" : sax []
 - in:  0 / out:  0
Scraping images for id "n04141327" : scabbard []
 - in:  0 / out:  0
Scraping images for id "n04141975" : scale []
 - in:  0 / out:  0
Scraping images for id "n04146614" : school_bus []
 - in:  0 / out:  0
Scraping images for id "n04147183" : schooner []
 - in:  0 / out:  0
Scraping images for id "n04149813" : scoreboard []
 - in:  0 / out:  0
Scraping images for id "n04152593" : screen []
 - in:  0 / out:  0
Scraping images for id "n04153751" : screw []
 - in:  0 / out:  0
Scraping images for id "n04154565" : screwdriver []
 - in:  0 / out:  0
Scraping images for id "n04162706" : seat_belt []
 - in:  0 / out:  0
Scraping images for id "n04179913" : sewing_machine []
 - in:  0 / out:  0
Scraping images for id "n04192698" : shield []
 - in:  0 / out:  0
Scraping images for id "n04200800" : shoe_shop []
 - in:  0 / out:  0
Scraping images for id "n04201297" : shoji []
 - in:  0 / out:  0
Scraping images for id "n04204238" : shopping_basket []
 - in:  0 / out:  0
Scraping images for id "n04204347" : shopping_cart []
 - in:  0 / out:  0
Scraping images for id "n04208210" : shovel []
 - in:  0 / out:  0
Scraping images for id "n04209133" : shower_cap []
 - in:  0 / out:  0
Scraping images for id "n04209239" : shower_curtain []
 - in:  0 / out:  0
Scraping images for id "n04228054" : ski []
 - in:  0 / out:  0
Scraping images for id "n04229816" : ski_mask []
 - in:  0 / out:  0
Scraping images for id "n04235860" : sleeping_bag []
 - in:  0 / out:  0
Scraping images for id "n04238763" : slide_rule []
 - in:  0 / out:  0
Scraping images for id "n04239074" : sliding_door []
 - in:  0 / out:  0
Scraping images for id "n04243546" : slot []
 - in:  0 / out:  0
Scraping images for id "n04251144" : snorkel

[]
 - in:  0 / out:  0
Scraping images for id "n04252077" : snowmobile []
 - in:  0 / out:  0
Scraping images for id "n04252225" : snowplow []
 - in:  0 / out:  0
Scraping images for id "n04254120" : soap_dispenser []
 - in:  0 / out:  0
Scraping images for id "n04254680" : soccer_ball []
 - in:  0 / out:  0
Scraping images for id "n04254777" : sock []
 - in:  0 / out:  0
Scraping images for id "n04258138" : solar_dish []
 - in:  0 / out:  0
Scraping images for id "n04259630" : sombrero []
 - in:  0 / out:  0
Scraping images for id "n04263257" : soup_bowl []
 - in:  0 / out:  0
Scraping images for id "n04264628" : space_bar []
 - in:  0 / out:  0
Scraping images for id "n04265275" : space_heater []
 - in:  0 / out:  0
Scraping images for id "n04266014" : space_shuttle []
 - in:  0 / out:  0
Scraping images for id "n04270147" : spatula []
 - in:  0 / out:  0
Scraping images for id "n04273569" : speedboat []
 - in:  0 / out:  0
Scraping images for id "n04275548" : spider_web []
 - in:  0 / out:  0
Scraping images for id "n04277352" : spindle []
 - in:  0 / out:  0
Scraping images for id "n04285008" : sports_car []
 - in:  0 / out:  0
Scraping images for id "n04286575" : spotlight []
 - in:  0 / out:  0
Scraping images for id "n04296562" : stage []
 - in:  0 / out:  0
Scraping images for id "n04310018" : steam_locomotive []
 - in:  0 / out:  0
Scraping images for id "n04311004" : steel_arch_bridge []
 - in:  0 / out:  0
Scraping images for id "n04311174" : steel_drum []
 - in:  0 / out:  0
Scraping images for id "n04317175" : stethoscope []
 - in:  0 / out:  0
Scraping images for id "n04325704" : stole []
 - in:  0 / out:  0
Scraping images for id "n04326547" : stone_wall []
 - in:  0 / out:  0
Scraping images for id "n04328186" : stopwatch []
 - in:  0 / out:  0
Scraping images for id "n04330267" : stove []
 - in:  0 / out:  0
Scraping images for id "n04332243" : strainer []
 - in:  0 / out:  0
Scraping images for id "n04335435" : streetcar []
 - in:  0 / out:  0
Scraping images for id "n04336792" : stretcher []
 - in:  0 / out:  0
Scraping images for id "n04344873" : studio_couch []
 - in:  0 / out:  0
Scraping images for id "n04346328" : stupa []
 - in:  0 / out:  0
Scraping images for id "n04347754" : submarine []
 - in:  0 / out:  0
Scraping images for id "n04350905" : suit []
 - in:  0 / out:  0
Scraping images for id "n04355338" : sundial []
 - in:  0 / out:  0
Scraping images for id "n04355933" : sunglass []
 - in:  0 / out:  0
Scraping images for id "n04356056" : sunglasses []
 - in:  0 / out:  0
Scraping images for id "n04357314" : sunscreen []
 - in:  0 / out:  0
Scraping images for id "n04366367" : suspension_bridge []
 - in:  0 / out:  0
Scraping images for id "n04367480" : swab []
 - in:  0 / out:  0
Scraping images for id "n04370456" : sweatshirt []
 - in:  0 / out:  0
Scraping images for id "n04371430" : swimming_trunks []
 - in:  0 / out:  0
Scraping images for id "n04371774" : swing []
 - in:  0 / out:  0
Scraping images for id "n04372370" : switch []
 - in:  0 / out:  0
Scraping images for id "n04376876" : syringe []
 - in:  0 / out:  0
Scraping images for id "n04380533" : table_lamp []
 - in:  0 / out:  0
Scraping images for id "n04389033" : tank []
 - in:  0 / out:  0
Scraping images for id "n04392985" : tape_player []
 - in:  0 / out:  0
Scraping images for id "n04398044" : teapot []
 - in:  0 / out:  0
Scraping images for id "n04399382" : teddy []
 - in:  0 / out:  0
Scraping images for id "n04404412" : television []
 - in:  0 / out:  0
Scraping images for id "n04409515" : tennis_ball []
 - in:  0 / out:  0
Scraping images for id "n04417672" : thatch []
 - in:  0 / out:  0
Scraping images for id "n04418357" : theater_curtain []
 - in:  0 / out:  0
Scraping images for id "n04423845" : thimble []
 - in:  0 / out:  0
Scraping images for id "n04428191" : thresher []
 - in:  0 / out:  0
Scraping images for id "n04429376" : throne []
 - in:  0 / out:  0
Scraping images for id "n04435653" : tile_roof []
 - in:  0 / out:  0
Scraping images for id "n04442312" : toaster []
 - in:  0 / out:  0
Scraping images for id "n04443257" : tobacco_shop []
 - in:  0 / out:  0
Scraping images for id "n04447861" : toilet_seat []
 - in:  0 / out:  0
Scraping images for id "n04456115" : torch []
 - in:  0 / out:  0
Scraping images for id "n04458633" : totem_pole []
 - in:  0 / out:  0
Scraping images for id "n04461696" : tow_truck []
 - in:  0 / out:  0
Scraping images for id "n04462240" : toyshop []
 - in:  0 / out:  0
Scraping images for id "n04465501" : tractor []
 - in:  0 / out:  0
Scraping images for id "n04467665" : trailer_truck []
 - in:  0 / out:  0
Scraping images for id "n04476259" : tray []
 - in:  0 / out:  0
Scraping images for id "n04479046" : trench_coat []
 - in:  0 / out:  0
Scraping images for id "n04482393" : tricycle []
 - in:  0 / out:  0
Scraping images for id "n04483307" : trimaran []
 - in:  0 / out:  0
Scraping images for id "n04485082" : tripod []
 - in:  0 / out:  0
Scraping images for id "n04486054" : triumphal_arch []
 - in:  0 / out:  0
Scraping images for id "n04487081" : trolleybus []
 - in:  0 / out:  0
Scraping images for id "n04487394" : trombone []
 - in:  0 / out:  0
Scraping images for id "n04493381" : tub []
 - in:  0 / out:  0
Scraping images for id "n04501370" : turnstile []
 - in:  0 / out:  0
Scraping images for id "n04505470" : typewriter_keyboard []
 - in:  0 / out:  0
Scraping images for id "n04507155" : umbrella []
 - in:  0 / out:  0
Scraping images for id "n04509417" : unicycle []
 - in:  0 / out:  0
Scraping images for id "n04515003" : upright []
 - in:  0 / out:  0
Scraping images for id "n04517823" : vacuum []
 - in:  0 / out:  0
Scraping images for id "n04522168" : vase []

 - in:  0 / out:  0
Scraping images for id "n04523525" : vault []
 - in:  0 / out:  0
Scraping images for id "n04525038" : velvet []
 - in:  0 / out:  0
Scraping images for id "n04525305" : vending_machine []
 - in:  0 / out:  0
Scraping images for id "n04532106" : vestment []
 - in:  0 / out:  0
Scraping images for id "n04532670" : viaduct []
 - in:  0 / out:  0
Scraping images for id "n04536866" : violin []
 - in:  0 / out:  0
Scraping images for id "n04540053" : volleyball []
 - in:  0 / out:  0
Scraping images for id "n04542943" : waffle_iron []
 - in:  0 / out:  0
Scraping images for id "n04548280" : wall_clock []
 - in:  0 / out:  0
Scraping images for id "n04548362" : wallet []
 - in:  0 / out:  0
Scraping images for id "n04550184" : wardrobe []
 - in:  0 / out:  0
Scraping images for id "n04552348" : warplane []
 - in:  0 / out:  0
Scraping images for id "n04553703" : washbasin []
 - in:  0 / out:  0
Scraping images for id "n04554684" : washer []
 - in:  0 / out:  0
Scraping images for id "n04557648" : water_bottle []
 - in:  0 / out:  0
Scraping images for id "n04560804" : water_jug []
 - in:  0 / out:  0
Scraping images for id "n04562935" : water_tower []
 - in:  0 / out:  0
Scraping images for id "n04579145" : whiskey_jug []
 - in:  0 / out:  0
Scraping images for id "n04579432" : whistle []
 - in:  0 / out:  0
Scraping images for id "n04584207" : wig []
 - in:  0 / out:  0
Scraping images for id "n04589890" : window_screen []
 - in:  0 / out:  0
Scraping images for id "n04590129" : window_shade []
 - in:  0 / out:  0
Scraping images for id "n04591157" : windsor_tie []
 - in:  0 / out:  0
Scraping images for id "n04591713" : wine_bottle []
 - in:  0 / out:  0
Scraping images for id "n04592741" : wing []
 - in:  0 / out:  0
Scraping images for id "n04596742" : wok []
 - in:  0 / out:  0
Scraping images for id "n04597913" : wooden_spoon []
 - in:  0 / out:  0
Scraping images for id "n04599235" : wool []
 - in:  0 / out:  0
Scraping images for id "n04604644" : worm_fence []
 - in:  0 / out:  0
Scraping images for id "n04606251" : wreck []
 - in:  0 / out:  0
Scraping images for id "n04612504" : yawl []
 - in:  0 / out:  0
Scraping images for id "n04613696" : yurt []
 - in:  0 / out:  0
Scraping images for id "n06359193" : web_site []
 - in:  0 / out:  0
Scraping images for id "n06596364" : comic_book []
 - in:  0 / out:  0
Scraping images for id "n06785654" : crossword_puzzle []
 - in:  0 / out:  0
Scraping images for id "n06794110" : street_sign []
 - in:  0 / out:  0
Scraping images for id "n06874185" : traffic_light []
 - in:  0 / out:  0
Scraping images for id "n07248320" : book_jacket []
 - in:  0 / out:  0
Scraping images for id "n07565083" : menu []
 - in:  0 / out:  0
Scraping images for id "n07579787" : plate []
 - in:  0 / out:  0
Scraping images for id "n07583066" : guacamole []
 - in:  0 / out:  0
Scraping images for id "n07584110" : consomme []
 - in:  0 / out:  0
Scraping images for id "n07590611" : hot_pot []
 - in:  0 / out:  0
Scraping images for id "n07613480" : trifle []
 - in:  0 / out:  0
Scraping images for id "n07614500" : ice_cream []
 - in:  0 / out:  0
Scraping images for id "n07615774" : ice_lolly []
 - in:  0 / out:  0
Scraping images for id "n07684084" : french_loaf []
 - in:  0 / out:  0
Scraping images for id "n07693725" : bagel []
 - in:  0 / out:  0
Scraping images for id "n07695742" : pretzel []
 - in:  0 / out:  0
Scraping images for id "n07697313" : cheeseburger []
 - in:  0 / out:  0
Scraping images for id "n07697537" : hotdog []
 - in:  0 / out:  0
Scraping images for id "n07711569" : mashed_potato []
 - in:  0 / out:  0
Scraping images for id "n07714571" : head_cabbage []
 - in:  0 / out:  0
Scraping images for id "n07714990" : broccoli []
 - in:  0 / out:  0
Scraping images for id "n07715103" : cauliflower []
 - in:  0 / out:  0
Scraping images for id "n07716358" : zucchini []
 - in:  0 / out:  0
Scraping images for id "n07716906" : spaghetti_squash []
 - in:  0 / out:  0
Scraping images for id "n07717410" : acorn_squash []
 - in:  0 / out:  0
Scraping images for id "n07717556" : butternut_squash []
 - in:  0 / out:  0
Scraping images for id "n07718472" : cucumber []
 - in:  0 / out:  0
Scraping images for id "n07718747" : artichoke []
 - in:  0 / out:  0
Scraping images for id "n07720875" : bell_pepper []
 - in:  0 / out:  0
Scraping images for id "n07730033" : cardoon []
 - in:  0 / out:  0
Scraping images for id "n07734744" : mushroom []
 - in:  0 / out:  0
Scraping images for id "n07742313" : granny_smith []
 - in:  0 / out:  0
Scraping images for id "n07745940" : strawberry []
 - in:  0 / out:  0
Scraping images for id "n07747607" : orange []
 - in:  0 / out:  0
Scraping images for id "n07749582" : lemon []
 - in:  0 / out:  0
Scraping images for id "n07753113" : fig []
 - in:  0 / out:  0
Scraping images for id "n07753275" : pineapple []
 - in:  0 / out:  0
Scraping images for id "n07753592" : banana []
 - in:  0 / out:  0
Scraping images for id "n07754684" : jackfruit []
 - in:  0 / out:  0
Scraping images for id "n07760859" : custard_apple []
 - in:  0 / out:  0
Scraping images for id "n07768694" : pomegranate []
 - in:  0 / out:  0
Scraping images for id "n07802026" : hay []
 - in:  0 / out:  0
Scraping images for id "n07831146" : carbonara []
 - in:  0 / out:  0
Scraping images for id "n07836838" : chocolate_sauce []
 - in:  0 / out:  0
Scraping images for id "n07860988" : dough []
 - in:  0 / out:  0
Scraping images for id "n07871810" : meat_loaf []
 - in:  0 / out:  0
Scraping images for id "n07873807" : pizza []
 - in:  0 / out:  0
Scraping images for id "n07875152" : potpie []
 - in:  0 / out:  0
Scraping images for id "n07880968" : burrito []
 - in:  0 / out:  0
Scraping images for id "n07892512" : red_wine

[]
 - in:  0 / out:  0
Scraping images for id "n07920052" : espresso []
 - in:  0 / out:  0
Scraping images for id "n07930864" : cup []
 - in:  0 / out:  0
Scraping images for id "n07932039" : eggnog []
 - in:  0 / out:  0
Scraping images for id "n09193705" : alp []
 - in:  0 / out:  0
Scraping images for id "n09229709" : bubble []
 - in:  0 / out:  0
Scraping images for id "n09246464" : cliff []
 - in:  0 / out:  0
Scraping images for id "n09256479" : coral_reef []
 - in:  0 / out:  0
Scraping images for id "n09288635" : geyser []
 - in:  0 / out:  0
Scraping images for id "n09332890" : lakeside []
 - in:  0 / out:  0
Scraping images for id "n09399592" : promontory []
 - in:  0 / out:  0
Scraping images for id "n09421951" : sandbar []
 - in:  0 / out:  0
Scraping images for id "n09428293" : seashore []
 - in:  0 / out:  0
Scraping images for id "n09468604" : valley []
 - in:  0 / out:  0
Scraping images for id "n09472597" : volcano []
 - in:  0 / out:  0
Scraping images for id "n09835506" : ballplayer []
 - in:  0 / out:  0
Scraping images for id "n10148035" : groom []
 - in:  0 / out:  0
Scraping images for id "n10565667" : scuba_diver []
 - in:  0 / out:  0
Scraping images for id "n11879895" : rapeseed []
 - in:  0 / out:  0
Scraping images for id "n11939491" : daisy []
 - in:  0 / out:  0
Scraping images for id "n12057211" : yellow_lady's_slipper []
 - in:  0 / out:  0
Scraping images for id "n12144580" : corn []
 - in:  0 / out:  0
Scraping images for id "n12267677" : acorn []
 - in:  0 / out:  0
Scraping images for id "n12620546" : hip []
 - in:  0 / out:  0
Scraping images for id "n12768682" : buckeye []
 - in:  0 / out:  0
Scraping images for id "n12985857" : coral_fungus []
 - in:  0 / out:  0
Scraping images for id "n12998815" : agaric []
 - in:  0 / out:  0
Scraping images for id "n13037406" : gyromitra []
 - in:  0 / out:  0
Scraping images for id "n13040303" : stinkhorn []
 - in:  0 / out:  0
Scraping images for id "n13044778" : earthstar []
 - in:  0 / out:  0
Scraping images for id "n13052670" : hen-of-the-woods []
 - in:  0 / out:  0
Scraping images for id "n13054560" : bolete []
 - in:  0 / out:  0
Scraping images for id "n13133613" : ear []
 - in:  0 / out:  0
Scraping images for id "n15075141" : toilet_tissue []
 - in:  0 / out:  0